{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archispark.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archispark.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD:          {{ .Values.secrets.dbPassword | required "secrets.dbPassword is required" | quote }}
{{- end }}
