{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archispark.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "archispark.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD:          {{ .Values.secrets.dbPassword | required "secrets.dbPassword is required" | quote }}
  BETTER_AUTH_SECRET:   {{ .Values.secrets.betterAuthSecret | required "secrets.betterAuthSecret is required" | quote }}
  SEED_ADMIN_PASSWORD:  {{ .Values.secrets.seedAdminPassword | default "" | quote }}
  SEED_USER_PASSWORD:   {{ .Values.secrets.seedUserPassword | default "" | quote }}
  REDIS_PASSWORD:       {{ .Values.secrets.redisPassword | default "" | quote }}
{{- end }}
