packages:
  - "apps/*"
  - "packages/*"
overrides:
  esbuild: ">=0.24.3"
  postcss: ">=8.5.10"
allowBuilds:
  bcryptjs: true
  better-sqlite3: true
  esbuild: true
  msw: true
  sharp: true
minimumReleaseAgeExclude:
  - shadcn@4.8.1
  - eslint-plugin-turbo@2.9.16
  - lucide-react@1.17.0
  - '@better-auth/core@1.6.14'
  - '@better-auth/drizzle-adapter@1.6.14'
  - '@better-auth/kysely-adapter@1.6.14'
  - '@better-auth/memory-adapter@1.6.14'
  - '@better-auth/mongo-adapter@1.6.14'
  - '@better-auth/prisma-adapter@1.6.14'
  - '@better-auth/telemetry@1.6.14'
  - better-auth@1.6.14
  - '@typescript-eslint/eslint-plugin@8.61.0'
  - '@typescript-eslint/parser@8.61.0'
  - '@typescript-eslint/project-service@8.61.0'
  - '@typescript-eslint/scope-manager@8.61.0'
  - '@typescript-eslint/tsconfig-utils@8.61.0'
  - '@typescript-eslint/type-utils@8.61.0'
  - '@typescript-eslint/types@8.61.0'
  - '@typescript-eslint/typescript-estree@8.61.0'
  - '@typescript-eslint/utils@8.61.0'
  - '@typescript-eslint/visitor-keys@8.61.0'
  - typescript-eslint@8.61.0
  - '@turbo/darwin-64@2.9.17'
  - '@turbo/darwin-arm64@2.9.17'
  - '@turbo/linux-64@2.9.17'
  - '@turbo/linux-arm64@2.9.17'
  - '@turbo/windows-64@2.9.17'
  - '@turbo/windows-arm64@2.9.17'
  - prettier@3.8.4
  - turbo@2.9.17
