/** Metadata for the built-in "ArchiMate Notation" system pack (seeded by
 *  packages/db/drizzle-pg/0023_image_packs.sql, generated by
 *  apps/server/scripts/generate-archimate-icon-pack.ts). */
export const SYSTEM_ARCHIMATE_PACK = {
  slug: "archimate",
  name: "ArchiMate Notation",
  description:
    "Standard ArchiMate 3.1 element icons, available to every organization.",
} as const
