// AUTO-GENERATED by /tmp/gen-icons.mjs — ArchiMate type icons.
// Glyphs extracted from Archi's reference SVG exports (models/exports/references),
// normalised to a top-right-corner frame: x in roughly [-26,0] (left of the
// element's right edge), y in [0,28] (below its top edge). A handful of element
// types whose reference exports lacked a corner glyph use hand-crafted standard
// ArchiMate notation (collaboration, interaction, role, contract, etc.).

export type IconPrim =
  | { tag: "path"; d: string; fill?: boolean }
  | { tag: "polygon"; points: number[]; fill?: boolean }
  | { tag: "polyline"; points: number[] }
  | { tag: "circle"; cx: number; cy: number; r: number; fill?: boolean }
  | { tag: "ellipse"; cx: number; cy: number; rx: number; ry: number; fill?: boolean }
  | { tag: "rect"; x: number; y: number; width: number; height: number; rx?: number; fill?: boolean };

export const ARCHIMATE_ICONS: Record<string, IconPrim[]> = {
  AndJunction: [{"tag":"circle","cx":-11,"cy":12,"r":4,"fill":true}],
  ApplicationCollaboration: [{"tag":"circle","cx":-14,"cy":12,"r":4},{"tag":"circle","cx":-9,"cy":12,"r":4}],
  ApplicationComponent: [{"tag":"path","d":"M-15 19 L-15 15 M-15 13 L-15 11 M-15 8 L-15 6 L-5 6 L-5 19 L-15.5 19 M-18 8 L-12 8 L-12 10.5 L-18 10.5 ZM-18 13 L-12 13 L-12 15.5 L-18 15.5 Z"}],
  ApplicationEvent: [{"tag":"path","d":"M-20 16 C-17.8 16 -16 14 -16 11.5 C-16 9 -17.8 7 -20 7 C-20 7 -20 7 -20 7"},{"tag":"path","d":"M-8 16 C-5.8 16 -4 14 -4 11.5 C-4 9 -5.8 7 -8 7 C-8 7 -8 7 -8 7 M-20 7 L-8 7 M-20 16 L-8 16"}],
  ApplicationFunction: [{"tag":"polygon","points":[-17,19,-17,10,-11,5,-5,10,-5,19,-11,13]}],
  ApplicationInteraction: [{"tag":"path","d":"M-11.5 8 A4 4 0 0 0 -11.5 16 Z","fill":true},{"tag":"circle","cx":-11.5,"cy":12,"r":4}],
  ApplicationInterface: [{"tag":"path","d":"M-19 12 L-13 12"},{"tag":"circle","cx":-9,"cy":12,"r":4}],
  ApplicationProcess: [{"tag":"polygon","points":[-18,11,-10,11,-10,8,-4,13,-10,18,-10,15,-18,15]}],
  ApplicationService: [{"tag":"rect","x":-21,"y":7,"width":16,"height":9,"rx":4}],
  Artifact: [{"tag":"path","d":"M-19 0 L-1 18 L-19 18"},{"tag":"path","d":"M-1 18 L-19 18 L-19 0"}],
  Assessment: [{"tag":"circle","cx":-11,"cy":10,"r":4}],
  BusinessActor: [{"tag":"circle","cx":-11,"cy":7,"r":2.5},{"tag":"path","d":"M-11 9.5 L-11 15 M-15 12 L-7 12 M-11 15 L-14 19 M-11 15 L-8 19"}],
  BusinessCollaboration: [{"tag":"circle","cx":-14,"cy":12,"r":4},{"tag":"circle","cx":-9,"cy":12,"r":4}],
  BusinessEvent: [{"tag":"path","d":"M-20 16 C-17.8 16 -16 14 -16 11.5 C-16 9 -17.8 7 -20 7 C-20 7 -20 7 -20 7"},{"tag":"path","d":"M-8 16 C-5.8 16 -4 14 -4 11.5 C-4 9 -5.8 7 -8 7 C-8 7 -8 7 -8 7 M-20 7 L-8 7 M-20 16 L-8 16"}],
  BusinessFunction: [{"tag":"polygon","points":[-17,19,-17,10,-11,5,-5,10,-5,19,-11,13]}],
  BusinessInteraction: [{"tag":"path","d":"M-11.5 8 A4 4 0 0 0 -11.5 16 Z","fill":true},{"tag":"circle","cx":-11.5,"cy":12,"r":4}],
  BusinessInterface: [{"tag":"path","d":"M-19 12 L-13 12"},{"tag":"circle","cx":-9,"cy":12,"r":4}],
  BusinessObject: [{"tag":"rect","x":-18,"y":6,"width":13,"height":10},{"tag":"path","d":"M-18 9 L-5 9"}],
  BusinessProcess: [{"tag":"polygon","points":[-18,11,-10,11,-10,8,-4,13,-10,18,-10,15,-18,15]}],
  BusinessRole: [{"tag":"circle","cx":-8,"cy":12,"r":4},{"tag":"path","d":"M-12 12 L-17 12 M-17 9 L-17 15"}],
  BusinessService: [{"tag":"rect","x":-21,"y":7,"width":16,"height":9,"rx":4}],
  Capability: [{"tag":"rect","x":-9,"y":5,"width":4,"height":4},{"tag":"rect","x":-13,"y":9,"width":4,"height":4},{"tag":"rect","x":-9,"y":9,"width":4,"height":4},{"tag":"rect","x":-17,"y":13,"width":4,"height":4},{"tag":"rect","x":-13,"y":13,"width":4,"height":4},{"tag":"rect","x":-9,"y":13,"width":4,"height":4}],
  CommunicationNetwork: [{"tag":"path","d":"M-14 16.5 C-14 15.1 -15.1 14 -16.5 14 C-17.9 14 -19 15.1 -19 16.5 C-19 17.9 -17.9 19 -16.5 19 C-15.1 19 -14 17.9 -14 16.5 ZM-12 8.5 C-12 7.1 -13.1 6 -14.5 6 C-15.9 6 -17 7.1 -17 8.5 C-17 9.9 -15.9 11 -14.5 11 C-13.1 11 -12 9.9 -12 8.5 ZM-4 8.5 C-4 7.1 -5.1 6 -6.5 6 C-7.9 6 -9 7.1 -9 8.5 C-9 9.9 -7.9 11 -6.5 11 C-5.1 11 -4 9.9 -4 8.5 ZM-6 16.5 C-6 15.1 -7.1 14 -8.5 14 C-9.9 14 -11 15.1 -11 16.5 C-11 17.9 -9.9 19 -8.5 19 C-7.1 19 -6 17.9 -6 16.5 ZM-16 14 L-15 11 M-8 14 L-7 11 M-14 16.5 L-11 16.5 M-12 8.5 L-9 8.5"}],
  Constraint: [{"tag":"polygon","points":[-19,8,-7,8,-11,17,-23,17]}],
  Contract: [{"tag":"rect","x":-18,"y":6,"width":13,"height":10},{"tag":"path","d":"M-18 9 L-5 9 M-18 13 L-5 13"}],
  CourseOfAction: [{"tag":"path","d":"M-22.4 12 L-16.4 13 L-19.4 18.2","fill":true},{"tag":"path","d":"M-19.5 15 C-21.9 15 -24 16.7 -24.4 19.1"},{"tag":"path","d":"M-4 9.5 C-4 5.9 -6.9 3 -10.5 3 C-14.1 3 -17 5.9 -17 9.5 C-17 13.1 -14.1 16 -10.5 16 C-6.9 16 -4 13.1 -4 9.5 ZM-6.5 9.5 C-6.5 7.3 -8.3 5.5 -10.5 5.5 C-12.7 5.5 -14.5 7.3 -14.5 9.5 C-14.5 11.7 -12.7 13.5 -10.5 13.5 C-8.3 13.5 -6.5 11.7 -6.5 9.5 ZM-9 9.5 C-9 8.7 -9.7 8 -10.5 8 C-11.3 8 -12 8.7 -12 9.5 C-12 10.3 -11.3 11 -10.5 11 C-9.7 11 -9 10.3 -9 9.5 ZM-10 9.5 C-10 9.2 -10.2 9 -10.5 9 C-10.8 9 -11 9.2 -11 9.5 C-11 9.8 -10.8 10 -10.5 10 C-10.2 10 -10 9.8 -10 9.5 Z"}],
  DataObject: [{"tag":"rect","x":-18,"y":6,"width":13,"height":10},{"tag":"path","d":"M-18 9 L-5 9"}],
  Deliverable: [{"tag":"path","d":"M-18 6 L-5 6 L-5 15 C-7 17 -9 13 -11 15 C-13 17 -16 13 -18 15 Z"}],
  Device: [{"tag":"rect","x":-16,"y":5,"width":11,"height":8,"rx":1.5},{"tag":"polygon","points":[-17,17,-14,13,-7,13,-4,17]}],
  DistributionNetwork: [{"tag":"path","d":"M-19 10 L-6 10 M-19 14 L-6 14 M-16 7 L-21 12 L-16 17 M-9 7 L-4 12 L-9 17"}],
  Driver: [{"tag":"path","d":"M-8 12.5 C-8 8.9 -10.9 6 -14.5 6 C-18.1 6 -21 8.9 -21 12.5 C-21 16.1 -18.1 19 -14.5 19 C-10.9 19 -8 16.1 -8 12.5 ZM-13 12.5 C-13 11.7 -13.7 11 -14.5 11 C-15.3 11 -16 11.7 -16 12.5 C-16 13.3 -15.3 14 -14.5 14 C-13.7 14 -13 13.3 -13 12.5 ZM-14 12.5 C-14 12.2 -14.2 12 -14.5 12 C-14.8 12 -15 12.2 -15 12.5 C-15 12.8 -14.8 13 -14.5 13 C-14.2 13 -14 12.8 -14 12.5 Z"},{"tag":"path","d":"M-23 12.5 L-6 12.5 M-14.5 4 L-14.5 21 M-20.5 6.5 L-8.5 18.5 M-20.5 18.5 L-8.5 6.5"}],
  Equipment: [{"tag":"polygon","points":[-8,21,-6,21,-6,19,-8,19,-9,17,-8,15,-9,14,-11,15,-13,14,-13,12,-15,12,-15,14,-17,15,-19,14,-20,15,-19,17,-20,19,-22,19,-22,21,-20,21,-19,23,-20,25,-19,26,-17,25,-15,26,-15,28,-13,28,-13,26,-11,25,-9,26,-8,25,-9,23]},{"tag":"path","d":"M-11 20 C-11 18.3 -12.3 17 -14 17 C-15.7 17 -17 18.3 -17 20 C-17 21.7 -15.7 23 -14 23 C-12.3 23 -11 21.7 -11 20 Z"},{"tag":"polygon","points":[-5,10,-4,10,-4,8,-5,8,-6,6,-6,5,-7,4,-8,5,-10,5,-11,4,-12,5,-12,6,-13,8,-14,8,-14,10,-13,10,-12,12,-12,13,-11,14,-10,13,-8,13,-7,14,-6,13,-6,12]},{"tag":"path","d":"M-7 9 C-7 7.9 -7.9 7 -9 7 C-10.1 7 -11 7.9 -11 9 C-11 10.1 -10.1 11 -9 11 C-7.9 11 -7 10.1 -7 9 Z"}],
  Facility: [{"tag":"polygon","points":[-20,17,-5,17,-5,11,-9,14,-9,11,-13,14,-13,11,-17,14,-17,5,-20,5]}],
  Gap: [{"tag":"ellipse","cx":-11,"cy":12,"rx":8,"ry":4}],
  Goal: [{"tag":"path","d":"M-7 12.5 C-7 8.9 -9.9 6 -13.5 6 C-17.1 6 -20 8.9 -20 12.5 C-20 16.1 -17.1 19 -13.5 19 C-9.9 19 -7 16.1 -7 12.5 ZM-9.5 12.5 C-9.5 10.3 -11.3 8.5 -13.5 8.5 C-15.7 8.5 -17.5 10.3 -17.5 12.5 C-17.5 14.7 -15.7 16.5 -13.5 16.5 C-11.3 16.5 -9.5 14.7 -9.5 12.5 ZM-12 12.5 C-12 11.7 -12.7 11 -13.5 11 C-14.3 11 -15 11.7 -15 12.5 C-15 13.3 -14.3 14 -13.5 14 C-12.7 14 -12 13.3 -12 12.5 ZM-13 12.5 C-13 12.2 -13.2 12 -13.5 12 C-13.8 12 -14 12.2 -14 12.5 C-14 12.8 -13.8 13 -13.5 13 C-13.2 13 -13 12.8 -13 12.5 Z"}],
  Grouping: [{"tag":"rect","x":-18,"y":6,"width":6,"height":3},{"tag":"rect","x":-18,"y":9,"width":13,"height":7}],
  ImplementationEvent: [{"tag":"path","d":"M-20 16 C-17.8 16 -16 14 -16 11.5 C-16 9 -17.8 7 -20 7 C-20 7 -20 7 -20 7"},{"tag":"path","d":"M-8 16 C-5.8 16 -4 14 -4 11.5 C-4 9 -5.8 7 -8 7 C-8 7 -8 7 -8 7 M-20 7 L-8 7 M-20 16 L-8 16"}],
  Junction: [{"tag":"circle","cx":-11,"cy":12,"r":4,"fill":true}],
  Location: [{"tag":"path","d":"M-4.3 11.7 C-3.4 9.1 -4.7 6.2 -7.3 5.3 C-9.9 4.4 -12.8 5.7 -13.7 8.3 C-14.1 9.4 -14.1 10.6 -13.7 11.7 L-9 20 Z"}],
  Material: [{"tag":"ellipse","cx":-11,"cy":12,"rx":7,"ry":5}],
  Meaning: [{"tag":"path","d":"M-17 15 C-20 15 -20 11 -16.5 11 C-16.5 7 -10 7 -9.5 11 C-6 10.5 -5 15 -8 15 Z"}],
  Node: [{"tag":"path","d":"M-18 8 L-7 8 L-7 19 L-18 19 ZM-18.2 8 L-14.8 5 L-4 5 L-4 16 L-7 19.2 M-7 8 L-4 5"}],
  OrJunction: [{"tag":"circle","cx":-11,"cy":12,"r":4}],
  Outcome: [{"tag":"path","d":"M-12 15.5 C-12 11.9 -14.9 9 -18.5 9 C-22.1 9 -25 11.9 -25 15.5 C-25 19.1 -22.1 22 -18.5 22 C-14.9 22 -12 19.1 -12 15.5 ZM-14.5 15.5 C-14.5 13.3 -16.3 11.5 -18.5 11.5 C-20.7 11.5 -22.5 13.3 -22.5 15.5 C-22.5 17.7 -20.7 19.5 -18.5 19.5 C-16.3 19.5 -14.5 17.7 -14.5 15.5 ZM-17 15.5 C-17 14.7 -17.7 14 -18.5 14 C-19.3 14 -20 14.7 -20 15.5 C-20 16.3 -19.3 17 -18.5 17 C-17.7 17 -17 16.3 -17 15.5 ZM-18 15.5 C-18 15.2 -18.2 15 -18.5 15 C-18.8 15 -19 15.2 -19 15.5 C-19 15.8 -18.8 16 -18.5 16 C-18.2 16 -18 15.8 -18 15.5 Z"},{"tag":"path","d":"M-19 16 L-9.5 6.5 M-12 9 L-11 4 M-12 9 L-7 8"}],
  Path: [{"tag":"path","d":"M-19 15 L-3 9 M-17 9 L-15 11 M-7 13 L-5 15"}],
  Plateau: [{"tag":"rect","x":-18,"y":7,"width":14,"height":3},{"tag":"rect","x":-18,"y":11,"width":14,"height":3},{"tag":"rect","x":-18,"y":15,"width":14,"height":3}],
  Principle: [{"tag":"rect","x":-20,"y":6,"width":12,"height":14,"rx":2},{"tag":"path","d":"M-14.5 8 L-14.5 15 M-13.5 8 L-13.5 15 M-14.5 16.5 L-14.5 18.5 M-13.5 16.5 L-13.5 18.5"}],
  Product: [{"tag":"rect","x":-18,"y":6,"width":13,"height":10},{"tag":"rect","x":-18,"y":6,"width":6,"height":3,"fill":true}],
  Representation: [{"tag":"path","d":"M-18 6 L-5 6 L-5 15 C-7 17 -9 13 -11 15 C-13 17 -16 13 -18 15 Z"}],
  Requirement: [{"tag":"polygon","points":[-19,8,-7,8,-11,17,-23,17]}],
  Resource: [{"tag":"rect","x":-20,"y":7,"width":15,"height":10,"rx":1.5},{"tag":"rect","x":-5,"y":10,"width":2,"height":4,"rx":0.5},{"tag":"path","d":"M-17 9 L-17 15 M-14 9 L-14 15 M-11 9 L-11 15"}],
  Stakeholder: [{"tag":"path","d":"M-17 9 C-19.2 9 -21 10.6 -21 12.5 C-21 14.4 -19.2 16 -17 16 L-10 16 M-17.5 9 L-10 9"},{"tag":"circle","cx":-9.5,"cy":12.5,"r":3.5}],
  SystemSoftware: [{"tag":"path","d":"M-11.5 8 C-14.5 8 -17 10.5 -17 13.5 C-17 16.5 -14.5 19 -11.5 19 C-8.5 19 -6 16.5 -6 13.5 C-6 10.5 -8.5 8 -11.5 8 ZM-6.7 16.3 C-4.1 14.7 -3.2 11.4 -4.7 8.8 C-6.3 6.1 -9.6 5.2 -12.2 6.7 C-13.1 7.2 -13.8 7.9 -14.3 8.8"}],
  TechnologyCollaboration: [{"tag":"circle","cx":-14,"cy":12,"r":4},{"tag":"circle","cx":-9,"cy":12,"r":4}],
  TechnologyEvent: [{"tag":"path","d":"M-20 16 C-17.8 16 -16 14 -16 11.5 C-16 9 -17.8 7 -20 7 C-20 7 -20 7 -20 7"},{"tag":"path","d":"M-8 16 C-5.8 16 -4 14 -4 11.5 C-4 9 -5.8 7 -8 7 C-8 7 -8 7 -8 7 M-20 7 L-8 7 M-20 16 L-8 16"}],
  TechnologyFunction: [{"tag":"polygon","points":[-17,19,-17,10,-11,5,-5,10,-5,19,-11,13]}],
  TechnologyInteraction: [{"tag":"path","d":"M-11.5 8 A4 4 0 0 0 -11.5 16 Z","fill":true},{"tag":"circle","cx":-11.5,"cy":12,"r":4}],
  TechnologyInterface: [{"tag":"path","d":"M-19 12 L-13 12"},{"tag":"circle","cx":-9,"cy":12,"r":4}],
  TechnologyProcess: [{"tag":"polygon","points":[-18,11,-10,11,-10,8,-4,13,-10,18,-10,15,-18,15]}],
  TechnologyService: [{"tag":"rect","x":-21,"y":7,"width":16,"height":9,"rx":4}],
  ValueStream: [{"tag":"polygon","points":[-19,7,-9,7,-4,12,-9,17,-19,17,-14,12]}],
  WorkPackage: [{"tag":"path","d":"M-9.3 12 C-8.4 9.7 -9.6 7.1 -12 6.3 C-14.3 5.4 -16.9 6.6 -17.7 9 C-18.6 11.3 -17.4 13.9 -15 14.7 C-14.4 15 -13.8 15 -13.1 15 M-13.5 15 L-7 15"},{"tag":"path","d":"M-7 12 L-3 15 L-7 18 Z","fill":true}],
};

/** Returns the icon primitives for an ArchiMate element type, or null if none. */
export function iconForType(type?: string | null): IconPrim[] | null {
  if (!type) return null;
  return ARCHIMATE_ICONS[type] ?? null;
}
