// Import of TYPE only, erased at compile time — never needs to be
// resolved at runtime. Relative path because plugins/ is not a pnpm
// workspace member (no @workspace/types specifier resolvable here).
import type { IconPluginManifest } from "../../packages/types/src/index"

const manifest: IconPluginManifest = {
  icons: [
    { slug: "activate", name: "Activate", file: "activate.svg" },
    {
      slug: "alexa-for-business",
      name: "Alexa For Business",
      file: "alexa-for-business.svg",
    },
    { slug: "amplify", name: "Amplify", file: "amplify.svg" },
    { slug: "api-gateway", name: "API Gateway", file: "api-gateway.svg" },
    { slug: "app-mesh", name: "App Mesh", file: "app-mesh.svg" },
    { slug: "app-runner", name: "App Runner", file: "app-runner.svg" },
    { slug: "appflow", name: "AppFlow", file: "appflow.svg" },
    {
      slug: "application-auto-scaling",
      name: "Application Auto Scaling",
      file: "application-auto-scaling.svg",
    },
    {
      slug: "application-composer",
      name: "Application Composer",
      file: "application-composer.svg",
    },
    {
      slug: "application-cost-profiler",
      name: "Application Cost Profiler",
      file: "application-cost-profiler.svg",
    },
    {
      slug: "application-discovery-service",
      name: "Application Discovery Service",
      file: "application-discovery-service.svg",
    },
    {
      slug: "application-migration-service",
      name: "Application Migration Service",
      file: "application-migration-service.svg",
    },
    { slug: "appstream", name: "AppStream", file: "appstream.svg" },
    { slug: "appsync", name: "AppSync", file: "appsync.svg" },
    { slug: "artifact", name: "Artifact", file: "artifact.svg" },
    { slug: "athena", name: "Athena", file: "athena.svg" },
    { slug: "audit-manager", name: "Audit Manager", file: "audit-manager.svg" },
    { slug: "aurora", name: "Aurora", file: "aurora.svg" },
    { slug: "backup", name: "Backup", file: "backup.svg" },
    { slug: "batch", name: "Batch", file: "batch.svg" },
    {
      slug: "billing-conductor",
      name: "Billing Conductor",
      file: "billing-conductor.svg",
    },
    { slug: "bottlerocket", name: "Bottlerocket", file: "bottlerocket.svg" },
    { slug: "braket", name: "Braket", file: "braket.svg" },
    { slug: "budgets", name: "Budgets", file: "budgets.svg" },
    {
      slug: "certificate-manager",
      name: "Certificate Manager",
      file: "certificate-manager.svg",
    },
    { slug: "chime-sdk", name: "Chime SDK", file: "chime-sdk.svg" },
    {
      slug: "chime-voice-connector",
      name: "Chime Voice Connector",
      file: "chime-voice-connector.svg",
    },
    { slug: "chime", name: "Chime", file: "chime.svg" },
    { slug: "clean-rooms", name: "Clean Rooms", file: "clean-rooms.svg" },
    { slug: "client-vpn", name: "Client VPN", file: "client-vpn.svg" },
    {
      slug: "cloud-control-api",
      name: "Cloud Control API",
      file: "cloud-control-api.svg",
    },
    {
      slug: "cloud-development-kit",
      name: "Cloud Development Kit",
      file: "cloud-development-kit.svg",
    },
    {
      slug: "cloud-directory",
      name: "Cloud Directory",
      file: "cloud-directory.svg",
    },
    { slug: "cloud-map", name: "Cloud Map", file: "cloud-map.svg" },
    { slug: "cloud-wan", name: "Cloud WAN", file: "cloud-wan.svg" },
    { slug: "cloud9", name: "Cloud9", file: "cloud9.svg" },
    { slug: "cloudfront", name: "CloudFront", file: "cloudfront.svg" },
    { slug: "cloudhsm", name: "CloudHSM", file: "cloudhsm.svg" },
    { slug: "cloudsearch", name: "CloudSearch", file: "cloudsearch.svg" },
    { slug: "cloudshell", name: "CloudShell", file: "cloudshell.svg" },
    { slug: "cloudwatch", name: "CloudWatch", file: "cloudwatch.svg" },
    { slug: "codeartifact", name: "CodeArtifact", file: "codeartifact.svg" },
    { slug: "codebuild", name: "CodeBuild", file: "codebuild.svg" },
    { slug: "codecatalyst", name: "CodeCatalyst", file: "codecatalyst.svg" },
    { slug: "codecommit", name: "CodeCommit", file: "codecommit.svg" },
    { slug: "codedeploy", name: "CodeDeploy", file: "codedeploy.svg" },
    { slug: "codepipeline", name: "CodePipeline", file: "codepipeline.svg" },
    { slug: "codestar", name: "CodeStar", file: "codestar.svg" },
    { slug: "cognito", name: "Cognito", file: "cognito.svg" },
    {
      slug: "command-line-interface",
      name: "Command Line Interface",
      file: "command-line-interface.svg",
    },
    {
      slug: "compute-optimizer",
      name: "Compute Optimizer",
      file: "compute-optimizer.svg",
    },
    { slug: "config", name: "Config", file: "config.svg" },
    { slug: "connect", name: "Connect", file: "connect.svg" },
    {
      slug: "console-mobile-application",
      name: "Console Mobile Application",
      file: "console-mobile-application.svg",
    },
    { slug: "control-tower", name: "Control Tower", file: "control-tower.svg" },
    { slug: "corretto", name: "Corretto", file: "corretto.svg" },
    {
      slug: "cost-and-usage-report",
      name: "Cost and Usage Report",
      file: "cost-and-usage-report.svg",
    },
    { slug: "cost-explorer", name: "Cost Explorer", file: "cost-explorer.svg" },
    { slug: "data-exchange", name: "Data Exchange", file: "data-exchange.svg" },
    { slug: "data-pipeline", name: "Data Pipeline", file: "data-pipeline.svg" },
    {
      slug: "database-migration-service",
      name: "Database Migration Service",
      file: "database-migration-service.svg",
    },
    { slug: "datasync", name: "DataSync", file: "datasync.svg" },
    { slug: "datazone", name: "DataZone", file: "datazone.svg" },
    { slug: "detective", name: "Detective", file: "detective.svg" },
    { slug: "device-farm", name: "Device Farm", file: "device-farm.svg" },
    {
      slug: "direct-connect",
      name: "Direct Connect",
      file: "direct-connect.svg",
    },
    {
      slug: "directory-service",
      name: "Directory Service",
      file: "directory-service.svg",
    },
    {
      slug: "distro-for-opentelemetry",
      name: "Distro for OpenTelemetry",
      file: "distro-for-opentelemetry.svg",
    },
    { slug: "documentdb", name: "DocumentDB", file: "documentdb.svg" },
    { slug: "dynamodb", name: "DynamoDB", file: "dynamodb.svg" },
    {
      slug: "ec2-auto-scaling",
      name: "EC2 Auto Scaling",
      file: "ec2-auto-scaling.svg",
    },
    {
      slug: "ec2-image-builder",
      name: "EC2 Image Builder",
      file: "ec2-image-builder.svg",
    },
    { slug: "ec2", name: "EC2", file: "ec2.svg" },
    { slug: "ecs-anywhere", name: "ECS Anywhere", file: "ecs-anywhere.svg" },
    { slug: "efs", name: "EFS", file: "efs.svg" },
    { slug: "eks-anywhere", name: "EKS Anywhere", file: "eks-anywhere.svg" },
    { slug: "eks-cloud", name: "EKS Cloud", file: "eks-cloud.svg" },
    { slug: "eks-distro", name: "EKS Distro", file: "eks-distro.svg" },
    {
      slug: "elastic-beanstalk",
      name: "Elastic Beanstalk",
      file: "elastic-beanstalk.svg",
    },
    {
      slug: "elastic-block-store",
      name: "Elastic Block Store",
      file: "elastic-block-store.svg",
    },
    {
      slug: "elastic-container-registry",
      name: "Elastic Container Registry",
      file: "elastic-container-registry.svg",
    },
    {
      slug: "elastic-container-service",
      name: "Elastic Container Service",
      file: "elastic-container-service.svg",
    },
    {
      slug: "elastic-disaster-recovery",
      name: "Elastic Disaster Recovery",
      file: "elastic-disaster-recovery.svg",
    },
    {
      slug: "elastic-fabric-adapter",
      name: "Elastic Fabric Adapter",
      file: "elastic-fabric-adapter.svg",
    },
    {
      slug: "elastic-kubernetes-service",
      name: "Elastic Kubernetes Service",
      file: "elastic-kubernetes-service.svg",
    },
    {
      slug: "elastic-load-balancing",
      name: "Elastic Load Balancing",
      file: "elastic-load-balancing.svg",
    },
    {
      slug: "elastic-transcoder",
      name: "Elastic Transcoder",
      file: "elastic-transcoder.svg",
    },
    { slug: "elasticache", name: "ElastiCache", file: "elasticache.svg" },
    {
      slug: "elemental-appliances-software",
      name: "Elemental Appliances & Software",
      file: "elemental-appliances-software.svg",
    },
    {
      slug: "elemental-conductor",
      name: "Elemental Conductor",
      file: "elemental-conductor.svg",
    },
    {
      slug: "elemental-delta",
      name: "Elemental Delta",
      file: "elemental-delta.svg",
    },
    {
      slug: "elemental-link",
      name: "Elemental Link",
      file: "elemental-link.svg",
    },
    {
      slug: "elemental-live",
      name: "Elemental Live",
      file: "elemental-live.svg",
    },
    {
      slug: "elemental-mediaconnect",
      name: "Elemental MediaConnect",
      file: "elemental-mediaconnect.svg",
    },
    {
      slug: "elemental-mediaconvert",
      name: "Elemental MediaConvert",
      file: "elemental-mediaconvert.svg",
    },
    {
      slug: "elemental-medialive",
      name: "Elemental MediaLive",
      file: "elemental-medialive.svg",
    },
    {
      slug: "elemental-mediapackage",
      name: "Elemental MediaPackage",
      file: "elemental-mediapackage.svg",
    },
    {
      slug: "elemental-mediastore",
      name: "Elemental MediaStore",
      file: "elemental-mediastore.svg",
    },
    {
      slug: "elemental-mediatailor",
      name: "Elemental MediaTailor",
      file: "elemental-mediatailor.svg",
    },
    {
      slug: "elemental-server",
      name: "Elemental Server",
      file: "elemental-server.svg",
    },
    { slug: "emr", name: "EMR", file: "emr.svg" },
    { slug: "eventbridge", name: "EventBridge", file: "eventbridge.svg" },
    {
      slug: "express-workflows",
      name: "Express Workflows",
      file: "express-workflows.svg",
    },
    { slug: "fargate", name: "Fargate", file: "fargate.svg" },
    {
      slug: "fault-injection-simulator",
      name: "Fault Injection Simulator",
      file: "fault-injection-simulator.svg",
    },
    { slug: "file-cache", name: "File Cache", file: "file-cache.svg" },
    { slug: "finspace", name: "FinSpace", file: "finspace.svg" },
    {
      slug: "firewall-manager",
      name: "Firewall Manager",
      file: "firewall-manager.svg",
    },
    { slug: "freertos", name: "FreeRTOS", file: "freertos.svg" },
    {
      slug: "fsx-for-lustre",
      name: "FSx for Lustre",
      file: "fsx-for-lustre.svg",
    },
    {
      slug: "fsx-for-netapp-ontap",
      name: "FSx for NetApp ONTAP",
      file: "fsx-for-netapp-ontap.svg",
    },
    {
      slug: "fsx-for-openzfs",
      name: "FSx for OpenZFS",
      file: "fsx-for-openzfs.svg",
    },
    { slug: "fsx-for-wfs", name: "FSx for WFS", file: "fsx-for-wfs.svg" },
    { slug: "fsx", name: "FSx", file: "fsx.svg" },
    { slug: "gamekit", name: "GameKit", file: "gamekit.svg" },
    { slug: "gamelift", name: "GameLift", file: "gamelift.svg" },
    { slug: "gamesparks", name: "GameSparks", file: "gamesparks.svg" },
    { slug: "genomics-cli", name: "Genomics CLI", file: "genomics-cli.svg" },
    {
      slug: "global-accelerator",
      name: "Global Accelerator",
      file: "global-accelerator.svg",
    },
    { slug: "glue-databrew", name: "Glue DataBrew", file: "glue-databrew.svg" },
    {
      slug: "glue-elastic-views",
      name: "Glue Elastic Views",
      file: "glue-elastic-views.svg",
    },
    { slug: "glue", name: "Glue", file: "glue.svg" },
    {
      slug: "ground-station",
      name: "Ground Station",
      file: "ground-station.svg",
    },
    { slug: "guardduty", name: "GuardDuty", file: "guardduty.svg" },
    { slug: "honeycode", name: "Honeycode", file: "honeycode.svg" },
    {
      slug: "iam-identity-center",
      name: "IAM Identity Center",
      file: "iam-identity-center.svg",
    },
    {
      slug: "identity-and-access-management",
      name: "Identity and Access Management",
      file: "identity-and-access-management.svg",
    },
    { slug: "inspector", name: "Inspector", file: "inspector.svg" },
    {
      slug: "interactive-video-service",
      name: "Interactive Video Service",
      file: "interactive-video-service.svg",
    },
    { slug: "iot-1-click", name: "IoT 1 Click", file: "iot-1-click.svg" },
    { slug: "iot-analytics", name: "IoT Analytics", file: "iot-analytics.svg" },
    { slug: "iot-button", name: "IoT Button", file: "iot-button.svg" },
    { slug: "iot-core", name: "IoT Core", file: "iot-core.svg" },
    {
      slug: "iot-device-defender",
      name: "IoT Device Defender",
      file: "iot-device-defender.svg",
    },
    {
      slug: "iot-device-management",
      name: "IoT Device Management",
      file: "iot-device-management.svg",
    },
    { slug: "iot-edukit", name: "IoT EduKit", file: "iot-edukit.svg" },
    { slug: "iot-events", name: "IoT Events", file: "iot-events.svg" },
    {
      slug: "iot-expresslink",
      name: "IoT ExpressLink",
      file: "iot-expresslink.svg",
    },
    { slug: "iot-fleetwise", name: "IoT FleetWise", file: "iot-fleetwise.svg" },
    {
      slug: "iot-greengrass",
      name: "IoT Greengrass",
      file: "iot-greengrass.svg",
    },
    {
      slug: "iot-roborunner",
      name: "IoT RoboRunner",
      file: "iot-roborunner.svg",
    },
    { slug: "iot-sitewise", name: "IoT SiteWise", file: "iot-sitewise.svg" },
    {
      slug: "iot-things-graph",
      name: "IoT Things Graph",
      file: "iot-things-graph.svg",
    },
    { slug: "iot-twinmaker", name: "IoT TwinMaker", file: "iot-twinmaker.svg" },
    { slug: "iq", name: "IQ", file: "iq.svg" },
    {
      slug: "key-management-service",
      name: "Key Management Service",
      file: "key-management-service.svg",
    },
    { slug: "keyspaces", name: "Keyspaces", file: "keyspaces.svg" },
    {
      slug: "kinesis-data-analytics",
      name: "Kinesis Data Analytics",
      file: "kinesis-data-analytics.svg",
    },
    {
      slug: "kinesis-data-streams",
      name: "Kinesis Data Streams",
      file: "kinesis-data-streams.svg",
    },
    {
      slug: "kinesis-firehose",
      name: "Kinesis Firehose",
      file: "kinesis-firehose.svg",
    },
    {
      slug: "kinesis-video-streams",
      name: "Kinesis Video Streams",
      file: "kinesis-video-streams.svg",
    },
    { slug: "kinesis", name: "Kinesis", file: "kinesis.svg" },
    {
      slug: "lake-formation",
      name: "Lake Formation",
      file: "lake-formation.svg",
    },
    { slug: "lambda", name: "Lambda", file: "lambda.svg" },
    { slug: "launch-wizard", name: "Launch Wizard", file: "launch-wizard.svg" },
    {
      slug: "license-manager",
      name: "License Manager",
      file: "license-manager.svg",
    },
    { slug: "lightsail", name: "Lightsail", file: "lightsail.svg" },
    { slug: "local-zones", name: "Local Zones", file: "local-zones.svg" },
    {
      slug: "location-service",
      name: "Location Service",
      file: "location-service.svg",
    },
    {
      slug: "lookout-for-metrics",
      name: "Lookout for Metrics",
      file: "lookout-for-metrics.svg",
    },
    {
      slug: "lookout-for-vision",
      name: "Lookout for Vision",
      file: "lookout-for-vision.svg",
    },
    { slug: "lumberyard", name: "Lumberyard", file: "lumberyard.svg" },
    { slug: "macie", name: "Macie", file: "macie.svg" },
    {
      slug: "mainframe-modernization",
      name: "Mainframe Modernization",
      file: "mainframe-modernization.svg",
    },
    {
      slug: "managed-blockchain",
      name: "Managed Blockchain",
      file: "managed-blockchain.svg",
    },
    {
      slug: "managed-grafana",
      name: "Managed Grafana",
      file: "managed-grafana.svg",
    },
    {
      slug: "managed-service-for-prometheus",
      name: "Managed Service for Prometheus",
      file: "managed-service-for-prometheus.svg",
    },
    {
      slug: "managed-services",
      name: "Managed Services",
      file: "managed-services.svg",
    },
    {
      slug: "managed-streaming-for-apache-kafka",
      name: "Managed Streaming for Apache Kafka",
      file: "managed-streaming-for-apache-kafka.svg",
    },
    {
      slug: "managed-workflows-for-apache-airflow",
      name: "Managed Workflows for Apache Airflow",
      file: "managed-workflows-for-apache-airflow.svg",
    },
    {
      slug: "management-console",
      name: "Management Console",
      file: "management-console.svg",
    },
    {
      slug: "marketplace-dark",
      name: "Marketplace Dark",
      file: "marketplace-dark.svg",
    },
    {
      slug: "marketplace-light",
      name: "Marketplace Light",
      file: "marketplace-light.svg",
    },
    {
      slug: "memorydb-for-redis",
      name: "MemoryDB for Redis",
      file: "memorydb-for-redis.svg",
    },
    {
      slug: "migration-evaluator",
      name: "Migration Evaluator",
      file: "migration-evaluator.svg",
    },
    { slug: "migration-hub", name: "Migration Hub", file: "migration-hub.svg" },
    { slug: "monitron", name: "Monitron", file: "monitron.svg" },
    { slug: "mq", name: "MQ", file: "mq.svg" },
    { slug: "neptune", name: "Neptune", file: "neptune.svg" },
    {
      slug: "network-firewall",
      name: "Network Firewall",
      file: "network-firewall.svg",
    },
    { slug: "neuron", name: "Neuron", file: "neuron.svg" },
    { slug: "nice-dcv", name: "NICE DCV", file: "nice-dcv.svg" },
    {
      slug: "nice-enginframe",
      name: "NICE EnginFrame",
      file: "nice-enginframe.svg",
    },
    { slug: "nimble-studio", name: "Nimble Studio", file: "nimble-studio.svg" },
    {
      slug: "nitro-enclaves",
      name: "Nitro Enclaves",
      file: "nitro-enclaves.svg",
    },
    { slug: "omics", name: "Omics", file: "omics.svg" },
    {
      slug: "open-3d-engine",
      name: "Open 3D Engine",
      file: "open-3d-engine.svg",
    },
    {
      slug: "opensearch-service",
      name: "OpenSearch Service",
      file: "opensearch-service.svg",
    },
    { slug: "opsworks", name: "OpsWorks", file: "opsworks.svg" },
    { slug: "organizations", name: "Organizations", file: "organizations.svg" },
    {
      slug: "outposts-family",
      name: "Outposts family",
      file: "outposts-family.svg",
    },
    { slug: "outposts-rack", name: "Outposts rack", file: "outposts-rack.svg" },
    {
      slug: "outposts-servers",
      name: "Outposts servers",
      file: "outposts-servers.svg",
    },
    { slug: "panorama", name: "Panorama", file: "panorama.svg" },
    {
      slug: "parallelcluster",
      name: "ParallelCluster",
      file: "parallelcluster.svg",
    },
    {
      slug: "personal-health-dashboard",
      name: "Personal Health Dashboard",
      file: "personal-health-dashboard.svg",
    },
    { slug: "personalize", name: "Personalize", file: "personalize.svg" },
    { slug: "pinpoint-apis", name: "Pinpoint APIs", file: "pinpoint-apis.svg" },
    { slug: "pinpoint", name: "Pinpoint", file: "pinpoint.svg" },
    { slug: "polly", name: "Polly", file: "polly.svg" },
    { slug: "private-5g", name: "Private 5G", file: "private-5g.svg" },
    {
      slug: "private-certificate-authority",
      name: "Private Certificate Authority",
      file: "private-certificate-authority.svg",
    },
    { slug: "privatelink", name: "PrivateLink", file: "privatelink.svg" },
    {
      slug: "professional-services",
      name: "Professional Services",
      file: "professional-services.svg",
    },
    { slug: "proton", name: "Proton", file: "proton.svg" },
    {
      slug: "quantum-ledger-database",
      name: "Quantum Ledger Database",
      file: "quantum-ledger-database.svg",
    },
    { slug: "quicksight", name: "QuickSight", file: "quicksight.svg" },
    { slug: "rds-on-vmware", name: "RDS on VMware", file: "rds-on-vmware.svg" },
    { slug: "rds", name: "RDS", file: "rds.svg" },
    {
      slug: "red-hat-openshift-service-on-aws",
      name: "Red Hat OpenShift Service on AWS",
      file: "red-hat-openshift-service-on-aws.svg",
    },
    { slug: "redshift", name: "Redshift", file: "redshift.svg" },
    { slug: "rekognition", name: "Rekognition", file: "rekognition.svg" },
    { slug: "repost", name: "rePost", file: "repost.svg" },
    {
      slug: "reserved-instance-reporting",
      name: "Reserved Instance Reporting",
      file: "reserved-instance-reporting.svg",
    },
    {
      slug: "resilience-hub",
      name: "Resilience Hub",
      file: "resilience-hub.svg",
    },
    {
      slug: "resource-access-manager",
      name: "Resource Access Manager",
      file: "resource-access-manager.svg",
    },
    {
      slug: "resource-explorer",
      name: "Resource Explorer",
      file: "resource-explorer.svg",
    },
    { slug: "robomaker", name: "RoboMaker", file: "robomaker.svg" },
    { slug: "route-53", name: "Route 53", file: "route-53.svg" },
    {
      slug: "s3-on-outposts",
      name: "S3 on Outposts",
      file: "s3-on-outposts.svg",
    },
    {
      slug: "sagemaker-ground-truth",
      name: "SageMaker Ground Truth",
      file: "sagemaker-ground-truth.svg",
    },
    {
      slug: "sagemaker-studio-lab",
      name: "SageMaker Studio Lab",
      file: "sagemaker-studio-lab.svg",
    },
    { slug: "sagemaker", name: "SageMaker", file: "sagemaker.svg" },
    { slug: "savings-plans", name: "Savings Plans", file: "savings-plans.svg" },
    {
      slug: "secrets-manager",
      name: "Secrets Manager",
      file: "secrets-manager.svg",
    },
    { slug: "security-hub", name: "Security Hub", file: "security-hub.svg" },
    { slug: "security-lake", name: "Security Lake", file: "security-lake.svg" },
    {
      slug: "server-migration-service",
      name: "Server Migration Service",
      file: "server-migration-service.svg",
    },
    {
      slug: "serverless-application-repository",
      name: "Serverless Application Repository",
      file: "serverless-application-repository.svg",
    },
    {
      slug: "service-catalog",
      name: "Service Catalog",
      file: "service-catalog.svg",
    },
    {
      slug: "service-management-connector",
      name: "Service Management Connector",
      file: "service-management-connector.svg",
    },
    { slug: "shield", name: "Shield", file: "shield.svg" },
    { slug: "signer", name: "Signer", file: "signer.svg" },
    {
      slug: "simple-email-service",
      name: "Simple Email Service",
      file: "simple-email-service.svg",
    },
    {
      slug: "simple-notification-service",
      name: "Simple Notification Service",
      file: "simple-notification-service.svg",
    },
    {
      slug: "simple-queue-service",
      name: "Simple Queue Service",
      file: "simple-queue-service.svg",
    },
    {
      slug: "simple-storage-service-glacier",
      name: "Simple Storage Service Glacier",
      file: "simple-storage-service-glacier.svg",
    },
    {
      slug: "simple-storage-service",
      name: "Simple Storage Service",
      file: "simple-storage-service.svg",
    },
    {
      slug: "simspace-weaver",
      name: "SimSpace Weaver",
      file: "simspace-weaver.svg",
    },
    {
      slug: "site-to-site-vpn",
      name: "Site to Site VPN",
      file: "site-to-site-vpn.svg",
    },
    { slug: "snowball-edge", name: "Snowball Edge", file: "snowball-edge.svg" },
    { slug: "snowball", name: "Snowball", file: "snowball.svg" },
    { slug: "snowcone", name: "Snowcone", file: "snowcone.svg" },
    { slug: "snowmobile", name: "Snowmobile", file: "snowmobile.svg" },
    {
      slug: "step-functions",
      name: "Step Functions",
      file: "step-functions.svg",
    },
    {
      slug: "storage-gateway",
      name: "Storage Gateway",
      file: "storage-gateway.svg",
    },
    { slug: "sumerian", name: "Sumerian", file: "sumerian.svg" },
    { slug: "supply-chain", name: "Supply Chain", file: "supply-chain.svg" },
    { slug: "support", name: "Support", file: "support.svg" },
    {
      slug: "systems-manager",
      name: "Systems Manager",
      file: "systems-manager.svg",
    },
    {
      slug: "tensorflow-on-aws",
      name: "TensorFlow on AWS",
      file: "tensorflow-on-aws.svg",
    },
    { slug: "textract", name: "Textract", file: "textract.svg" },
    {
      slug: "thinkbox-deadline",
      name: "Thinkbox Deadline",
      file: "thinkbox-deadline.svg",
    },
    {
      slug: "thinkbox-frost",
      name: "Thinkbox Frost",
      file: "thinkbox-frost.svg",
    },
    {
      slug: "thinkbox-krakatoa",
      name: "Thinkbox Krakatoa",
      file: "thinkbox-krakatoa.svg",
    },
    {
      slug: "thinkbox-sequoia",
      name: "Thinkbox Sequoia",
      file: "thinkbox-sequoia.svg",
    },
    {
      slug: "thinkbox-stoke",
      name: "Thinkbox Stoke",
      file: "thinkbox-stoke.svg",
    },
    {
      slug: "thinkbox-xmesh",
      name: "Thinkbox XMesh",
      file: "thinkbox-xmesh.svg",
    },
    { slug: "timestream", name: "Timestream", file: "timestream.svg" },
    {
      slug: "tools-and-sdks",
      name: "Tools and SDKs",
      file: "tools-and-sdks.svg",
    },
    { slug: "torchserve", name: "TorchServe", file: "torchserve.svg" },
    {
      slug: "training-certification",
      name: "Training Certification",
      file: "training-certification.svg",
    },
    { slug: "transcribe", name: "Transcribe", file: "transcribe.svg" },
    {
      slug: "transfer-family",
      name: "Transfer Family",
      file: "transfer-family.svg",
    },
    {
      slug: "transit-gateway",
      name: "Transit Gateway",
      file: "transit-gateway.svg",
    },
    { slug: "translate", name: "Translate", file: "translate.svg" },
    {
      slug: "trusted-advisor",
      name: "Trusted Advisor",
      file: "trusted-advisor.svg",
    },
    {
      slug: "verified-access",
      name: "Verified Access",
      file: "verified-access.svg",
    },
    {
      slug: "verified-permissions",
      name: "Verified Permissions",
      file: "verified-permissions.svg",
    },
    {
      slug: "virtual-private-cloud",
      name: "Virtual Private Cloud",
      file: "virtual-private-cloud.svg",
    },
    {
      slug: "vmware-cloud-on-aws",
      name: "VMware Cloud on AWS",
      file: "vmware-cloud-on-aws.svg",
    },
    { slug: "vpc-lattice", name: "VPC Lattice", file: "vpc-lattice.svg" },
    { slug: "waf", name: "WAF", file: "waf.svg" },
    { slug: "wavelength", name: "Wavelength", file: "wavelength.svg" },
    {
      slug: "well-architected-tool",
      name: "Well Architected Tool",
      file: "well-architected-tool.svg",
    },
    { slug: "wickr", name: "Wickr", file: "wickr.svg" },
    { slug: "workdocs-sdk", name: "WorkDocs SDK", file: "workdocs-sdk.svg" },
    { slug: "workdocs", name: "WorkDocs", file: "workdocs.svg" },
    { slug: "worklink", name: "WorkLink", file: "worklink.svg" },
    { slug: "workmail", name: "WorkMail", file: "workmail.svg" },
    {
      slug: "workspaces-family",
      name: "WorkSpaces Family",
      file: "workspaces-family.svg",
    },
    { slug: "x-ray", name: "X Ray", file: "x-ray.svg" },
  ],
}

export default manifest
