// Import of TYPE only, erased at compile time — never needs to be
// resolved at runtime. Relative path because plugins/ is not a pnpm
// workspace member (no @workspace/types specifier resolvable here).
import type { IconPluginManifest } from "../../packages/types/src/index"

const manifest: IconPluginManifest = {
  icons: [
    { slug: "abs-member", name: "ABS Member", file: "abs-member.svg" },
    {
      slug: "active-directory-connect-health",
      name: "Active Directory Connect Health",
      file: "active-directory-connect-health.svg",
    },
    { slug: "activity-log", name: "Activity Log", file: "activity-log.svg" },
    {
      slug: "administrative-units",
      name: "Administrative Units",
      file: "administrative-units.svg",
    },
    { slug: "advisor", name: "Advisor", file: "advisor.svg" },
    {
      slug: "agentic-web-apps",
      name: "Agentic Web Apps",
      file: "agentic-web-apps.svg",
    },
    { slug: "ai-at-edge", name: "AI at Edge", file: "ai-at-edge.svg" },
    { slug: "ai-foundry", name: "AI Foundry", file: "ai-foundry.svg" },
    { slug: "ai-gateway", name: "AI Gateway", file: "ai-gateway.svg" },
    { slug: "ai-studio", name: "AI Studio", file: "ai-studio.svg" },
    { slug: "aks-automatic", name: "AKS Automatic", file: "aks-automatic.svg" },
    { slug: "aks-istio", name: "AKS Istio", file: "aks-istio.svg" },
    {
      slug: "aks-network-policy",
      name: "AKS Network Policy",
      file: "aks-network-policy.svg",
    },
    { slug: "alerts", name: "Alerts", file: "alerts.svg" },
    { slug: "all-resources", name: "All Resources", file: "all-resources.svg" },
    {
      slug: "analysis-services",
      name: "Analysis Services",
      file: "analysis-services.svg",
    },
    {
      slug: "anomaly-detector",
      name: "Anomaly Detector",
      file: "anomaly-detector.svg",
    },
    { slug: "api-center", name: "API Center", file: "api-center.svg" },
    {
      slug: "api-connections",
      name: "API Connections",
      file: "api-connections.svg",
    },
    {
      slug: "api-management-services",
      name: "API Management Services",
      file: "api-management-services.svg",
    },
    { slug: "api-proxy", name: "API Proxy", file: "api-proxy.svg" },
    {
      slug: "app-compliance-automation",
      name: "App Compliance Automation",
      file: "app-compliance-automation.svg",
    },
    {
      slug: "app-configuration",
      name: "App Configuration",
      file: "app-configuration.svg",
    },
    {
      slug: "app-registrations",
      name: "App Registrations",
      file: "app-registrations.svg",
    },
    {
      slug: "app-service-certificates",
      name: "App Service Certificates",
      file: "app-service-certificates.svg",
    },
    {
      slug: "app-service-domains",
      name: "App Service Domains",
      file: "app-service-domains.svg",
    },
    {
      slug: "app-service-environments",
      name: "App Service Environments",
      file: "app-service-environments.svg",
    },
    {
      slug: "app-service-plans",
      name: "App Service Plans",
      file: "app-service-plans.svg",
    },
    { slug: "app-services", name: "App Services", file: "app-services.svg" },
    {
      slug: "app-space-component",
      name: "App Space Component",
      file: "app-space-component.svg",
    },
    { slug: "app-space", name: "App Space", file: "app-space.svg" },
    { slug: "applens", name: "Applens", file: "applens.svg" },
    {
      slug: "application-gateway-containers",
      name: "Application Gateway Containers",
      file: "application-gateway-containers.svg",
    },
    {
      slug: "application-gateways",
      name: "Application Gateways",
      file: "application-gateways.svg",
    },
    {
      slug: "application-group",
      name: "Application Group",
      file: "application-group.svg",
    },
    {
      slug: "application-insights",
      name: "Application Insights",
      file: "application-insights.svg",
    },
    {
      slug: "application-security-groups",
      name: "Application Security Groups",
      file: "application-security-groups.svg",
    },
    { slug: "aquila", name: "Aquila", file: "aquila.svg" },
    {
      slug: "arc-data-services",
      name: "Arc Data services",
      file: "arc-data-services.svg",
    },
    {
      slug: "arc-kubernetes",
      name: "Arc Kubernetes",
      file: "arc-kubernetes.svg",
    },
    { slug: "arc-machines", name: "Arc Machines", file: "arc-machines.svg" },
    {
      slug: "arc-postgresql",
      name: "Arc PostgreSQL",
      file: "arc-postgresql.svg",
    },
    {
      slug: "arc-sql-managed-instance",
      name: "Arc SQL Managed Instance",
      file: "arc-sql-managed-instance.svg",
    },
    {
      slug: "arc-sql-server",
      name: "Arc SQL Server",
      file: "arc-sql-server.svg",
    },
    {
      slug: "atm-multistack",
      name: "ATM Multistack",
      file: "atm-multistack.svg",
    },
    { slug: "auto-scale", name: "Auto Scale", file: "auto-scale.svg" },
    {
      slug: "automanaged-vm",
      name: "Automanaged VM",
      file: "automanaged-vm.svg",
    },
    {
      slug: "automation-accounts",
      name: "Automation Accounts",
      file: "automation-accounts.svg",
    },
    {
      slug: "availability-sets",
      name: "Availability Sets",
      file: "availability-sets.svg",
    },
    { slug: "avs-vm", name: "AVS VM", file: "avs-vm.svg" },
    { slug: "azure-a", name: "Azure A", file: "azure-a.svg" },
    {
      slug: "azure-access-point",
      name: "Azure Access Point",
      file: "azure-access-point.svg",
    },
    { slug: "azure-ad-b2c", name: "Azure AD B2C", file: "azure-ad-b2c.svg" },
    {
      slug: "azure-ai-foundry-iq",
      name: "Azure AI Foundry IQ",
      file: "azure-ai-foundry-iq.svg",
    },
    {
      slug: "azure-api-for-fhir",
      name: "Azure API for FHIR",
      file: "azure-api-for-fhir.svg",
    },
    {
      slug: "azure-app-testing",
      name: "Azure App Testing",
      file: "azure-app-testing.svg",
    },
    {
      slug: "azure-applied-ai-services",
      name: "Azure Applied AI Services",
      file: "azure-applied-ai-services.svg",
    },
    { slug: "azure-arc", name: "Azure Arc", file: "azure-arc.svg" },
    {
      slug: "azure-backup-center",
      name: "Azure Backup Center",
      file: "azure-backup-center.svg",
    },
    {
      slug: "azure-blockchain-service",
      name: "Azure Blockchain Service",
      file: "azure-blockchain-service.svg",
    },
    {
      slug: "azure-center-for-sap",
      name: "Azure Center for SAP",
      file: "azure-center-for-sap.svg",
    },
    {
      slug: "azure-chaos-studio",
      name: "Azure Chaos Studio",
      file: "azure-chaos-studio.svg",
    },
    {
      slug: "azure-cloud-shell",
      name: "Azure Cloud Shell",
      file: "azure-cloud-shell.svg",
    },
    {
      slug: "azure-communication-services",
      name: "Azure Communication Services",
      file: "azure-communication-services.svg",
    },
    {
      slug: "azure-communications-gateway",
      name: "Azure Communications Gateway",
      file: "azure-communications-gateway.svg",
    },
    {
      slug: "azure-compute-galleries",
      name: "Azure Compute Galleries",
      file: "azure-compute-galleries.svg",
    },
    {
      slug: "azure-consumption-commitment",
      name: "Azure Consumption Commitment",
      file: "azure-consumption-commitment.svg",
    },
    {
      slug: "azure-container-storage",
      name: "Azure Container Storage",
      file: "azure-container-storage.svg",
    },
    {
      slug: "azure-cosmos-db",
      name: "Azure Cosmos DB",
      file: "azure-cosmos-db.svg",
    },
    {
      slug: "azure-data-catalog",
      name: "Azure Data Catalog",
      file: "azure-data-catalog.svg",
    },
    {
      slug: "azure-data-explorer-clusters",
      name: "Azure Data Explorer Clusters",
      file: "azure-data-explorer-clusters.svg",
    },
    {
      slug: "azure-data-sharing",
      name: "Azure Data Sharing",
      file: "azure-data-sharing.svg",
    },
    {
      slug: "azure-data-transfer",
      name: "Azure Data Transfer",
      file: "azure-data-transfer.svg",
    },
    {
      slug: "azure-database-mariadb-server",
      name: "Azure Database MariaDB Server",
      file: "azure-database-mariadb-server.svg",
    },
    {
      slug: "azure-database-migration-services",
      name: "Azure Database Migration Services",
      file: "azure-database-migration-services.svg",
    },
    {
      slug: "azure-database-mysql-server",
      name: "Azure Database MySQL Server",
      file: "azure-database-mysql-server.svg",
    },
    {
      slug: "azure-database-postgresql-server-group",
      name: "Azure Database PostgreSQL Server Group",
      file: "azure-database-postgresql-server-group.svg",
    },
    {
      slug: "azure-database-postgresql-server",
      name: "Azure Database PostgreSQL Server",
      file: "azure-database-postgresql-server.svg",
    },
    {
      slug: "azure-databox-gateway",
      name: "Azure Databox Gateway",
      file: "azure-databox-gateway.svg",
    },
    {
      slug: "azure-databricks",
      name: "Azure Databricks",
      file: "azure-databricks.svg",
    },
    {
      slug: "azure-deployment-environments",
      name: "Azure Deployment Environments",
      file: "azure-deployment-environments.svg",
    },
    {
      slug: "azure-dev-tunnels",
      name: "Azure Dev Tunnels",
      file: "azure-dev-tunnels.svg",
    },
    { slug: "azure-devops", name: "Azure DevOps", file: "azure-devops.svg" },
    {
      slug: "azure-documentdb",
      name: "Azure DocumentDB",
      file: "azure-documentdb.svg",
    },
    {
      slug: "azure-edge-hardware-center",
      name: "Azure Edge Hardware Center",
      file: "azure-edge-hardware-center.svg",
    },
    {
      slug: "azure-enclaves",
      name: "Azure Enclaves",
      file: "azure-enclaves.svg",
    },
    {
      slug: "azure-experimentation-studio",
      name: "Azure Experimentation Studio",
      file: "azure-experimentation-studio.svg",
    },
    {
      slug: "azure-fileshares",
      name: "Azure Fileshares",
      file: "azure-fileshares.svg",
    },
    {
      slug: "azure-firewall-manager",
      name: "Azure Firewall Manager",
      file: "azure-firewall-manager.svg",
    },
    {
      slug: "azure-firewall-policy",
      name: "Azure Firewall Policy",
      file: "azure-firewall-policy.svg",
    },
    {
      slug: "azure-hcp-cache",
      name: "Azure HCP Cache",
      file: "azure-hcp-cache.svg",
    },
    {
      slug: "azure-hpc-workbenches",
      name: "Azure HPC Workbenches",
      file: "azure-hpc-workbenches.svg",
    },
    {
      slug: "azure-hybrid-center",
      name: "Azure Hybrid Center",
      file: "azure-hybrid-center.svg",
    },
    {
      slug: "azure-information-protection",
      name: "Azure Information Protection",
      file: "azure-information-protection.svg",
    },
    {
      slug: "azure-iot-operations",
      name: "Azure IoT Operations",
      file: "azure-iot-operations.svg",
    },
    {
      slug: "azure-lighthouse",
      name: "Azure Lighthouse",
      file: "azure-lighthouse.svg",
    },
    { slug: "azure-linux", name: "Azure Linux", file: "azure-linux.svg" },
    {
      slug: "azure-load-testing",
      name: "Azure Load Testing",
      file: "azure-load-testing.svg",
    },
    { slug: "azure-local", name: "Azure Local", file: "azure-local.svg" },
    {
      slug: "azure-machine-learning",
      name: "Azure Machine Learning",
      file: "azure-machine-learning.svg",
    },
    {
      slug: "azure-managed-grafana",
      name: "Azure Managed Grafana",
      file: "azure-managed-grafana.svg",
    },
    {
      slug: "azure-managed-redis",
      name: "Azure Managed Redis",
      file: "azure-managed-redis.svg",
    },
    {
      slug: "azure-maps-accounts",
      name: "Azure Maps Accounts",
      file: "azure-maps-accounts.svg",
    },
    {
      slug: "azure-media-service",
      name: "Azure Media Service",
      file: "azure-media-service.svg",
    },
    { slug: "azure-migrate", name: "Azure Migrate", file: "azure-migrate.svg" },
    {
      slug: "azure-monitor-dashboard",
      name: "Azure Monitor Dashboard",
      file: "azure-monitor-dashboard.svg",
    },
    {
      slug: "azure-monitor-pipeline",
      name: "Azure Monitor Pipeline",
      file: "azure-monitor-pipeline.svg",
    },
    {
      slug: "azure-monitors-for-sap-solutions",
      name: "Azure Monitors for SAP Solutions",
      file: "azure-monitors-for-sap-solutions.svg",
    },
    {
      slug: "azure-netapp-files",
      name: "Azure NetApp Files",
      file: "azure-netapp-files.svg",
    },
    {
      slug: "azure-network-function-manager-functions",
      name: "Azure Network Function Manager Functions",
      file: "azure-network-function-manager-functions.svg",
    },
    {
      slug: "azure-network-function-manager",
      name: "Azure Network Function Manager",
      file: "azure-network-function-manager.svg",
    },
    {
      slug: "azure-object-understanding",
      name: "Azure Object Understanding",
      file: "azure-object-understanding.svg",
    },
    { slug: "azure-openai", name: "Azure OpenAI", file: "azure-openai.svg" },
    {
      slug: "azure-operator-5g-core",
      name: "Azure Operator 5G Core",
      file: "azure-operator-5g-core.svg",
    },
    {
      slug: "azure-operator-insights",
      name: "Azure Operator Insights",
      file: "azure-operator-insights.svg",
    },
    {
      slug: "azure-operator-nexus",
      name: "Azure Operator Nexus",
      file: "azure-operator-nexus.svg",
    },
    {
      slug: "azure-operator-service-manager",
      name: "Azure Operator Service Manager",
      file: "azure-operator-service-manager.svg",
    },
    { slug: "azure-orbital", name: "Azure Orbital", file: "azure-orbital.svg" },
    {
      slug: "azure-programmable-connectivity",
      name: "Azure Programmable Connectivity",
      file: "azure-programmable-connectivity.svg",
    },
    { slug: "azure-quotas", name: "Azure Quotas", file: "azure-quotas.svg" },
    {
      slug: "azure-red-hat-openshift",
      name: "Azure Red Hat OpenShift",
      file: "azure-red-hat-openshift.svg",
    },
    {
      slug: "azure-sentinel",
      name: "Azure Sentinel",
      file: "azure-sentinel.svg",
    },
    {
      slug: "azure-service-bus",
      name: "Azure Service Bus",
      file: "azure-service-bus.svg",
    },
    { slug: "azure-sphere", name: "Azure Sphere", file: "azure-sphere.svg" },
    {
      slug: "azure-spring-apps",
      name: "Azure Spring Apps",
      file: "azure-spring-apps.svg",
    },
    {
      slug: "azure-sql-edge",
      name: "Azure SQL Edge",
      file: "azure-sql-edge.svg",
    },
    {
      slug: "azure-sql-server-stretch-databases",
      name: "Azure SQL Server Stretch Databases",
      file: "azure-sql-server-stretch-databases.svg",
    },
    { slug: "azure-sql-vm", name: "Azure SQL VM", file: "azure-sql-vm.svg" },
    { slug: "azure-sql", name: "Azure SQL", file: "azure-sql.svg" },
    {
      slug: "azure-stack-hci-sizer",
      name: "Azure Stack HCI Sizer",
      file: "azure-stack-hci-sizer.svg",
    },
    {
      slug: "azure-storage-mover",
      name: "Azure Storage Mover",
      file: "azure-storage-mover.svg",
    },
    {
      slug: "azure-support-center-blue",
      name: "Azure Support Center Blue",
      file: "azure-support-center-blue.svg",
    },
    {
      slug: "azure-sustainability",
      name: "Azure Sustainability",
      file: "azure-sustainability.svg",
    },
    {
      slug: "azure-synapse-analytics",
      name: "Azure Synapse Analytics",
      file: "azure-synapse-analytics.svg",
    },
    {
      slug: "azure-token-service",
      name: "Azure Token Service",
      file: "azure-token-service.svg",
    },
    {
      slug: "azure-video-indexer",
      name: "Azure Video Indexer",
      file: "azure-video-indexer.svg",
    },
    {
      slug: "azure-virtual-desktop",
      name: "Azure Virtual Desktop",
      file: "azure-virtual-desktop.svg",
    },
    {
      slug: "azure-vmware-solution",
      name: "Azure VMware Solution",
      file: "azure-vmware-solution.svg",
    },
    {
      slug: "azure-workbooks",
      name: "Azure Workbooks",
      file: "azure-workbooks.svg",
    },
    {
      slug: "azureattestation",
      name: "AzureAttestation",
      file: "azureattestation.svg",
    },
    { slug: "azurite", name: "Azurite", file: "azurite.svg" },
    { slug: "backlog", name: "Backlog", file: "backlog.svg" },
    { slug: "backup-vault", name: "Backup Vault", file: "backup-vault.svg" },
    {
      slug: "bare-metal-infrastructure",
      name: "Bare Metal Infrastructure",
      file: "bare-metal-infrastructure.svg",
    },
    { slug: "bastions", name: "Bastions", file: "bastions.svg" },
    {
      slug: "batch-accounts",
      name: "Batch Accounts",
      file: "batch-accounts.svg",
    },
    { slug: "batch-ai", name: "Batch AI", file: "batch-ai.svg" },
    { slug: "biz-talk", name: "Biz Talk", file: "biz-talk.svg" },
    { slug: "blob-block", name: "Blob Block", file: "blob-block.svg" },
    { slug: "blob-page", name: "Blob Page", file: "blob-page.svg" },
    {
      slug: "blockchain-applications",
      name: "Blockchain Applications",
      file: "blockchain-applications.svg",
    },
    { slug: "blueprints", name: "Blueprints", file: "blueprints.svg" },
    { slug: "bonsai", name: "Bonsai", file: "bonsai.svg" },
    { slug: "bot-services", name: "Bot Services", file: "bot-services.svg" },
    { slug: "branch", name: "Branch", file: "branch.svg" },
    { slug: "breeze", name: "Breeze", file: "breeze.svg" },
    { slug: "browser", name: "Browser", file: "browser.svg" },
    { slug: "bug", name: "Bug", file: "bug.svg" },
    { slug: "builds", name: "Builds", file: "builds.svg" },
    {
      slug: "business-process-tracking",
      name: "Business Process Tracking",
      file: "business-process-tracking.svg",
    },
    { slug: "cache-redis", name: "Cache Redis", file: "cache-redis.svg" },
    { slug: "cache", name: "Cache", file: "cache.svg" },
    {
      slug: "capacity-reservation-groups",
      name: "Capacity Reservation Groups",
      file: "capacity-reservation-groups.svg",
    },
    { slug: "cdn-profiles", name: "CDN Profiles", file: "cdn-profiles.svg" },
    {
      slug: "central-service-instance-for-sap",
      name: "Central Service Instance For SAP",
      file: "central-service-instance-for-sap.svg",
    },
    { slug: "ceres", name: "Ceres", file: "ceres.svg" },
    {
      slug: "change-analysis",
      name: "Change Analysis",
      file: "change-analysis.svg",
    },
    { slug: "client-apps", name: "Client Apps", file: "client-apps.svg" },
    {
      slug: "cloud-services-classic",
      name: "Cloud Services (Classic)",
      file: "cloud-services-classic.svg",
    },
    {
      slug: "cloud-services-extended-support",
      name: "Cloud Services (extended support)",
      file: "cloud-services-extended-support.svg",
    },
    { slug: "cloudtest", name: "CloudTest", file: "cloudtest.svg" },
    {
      slug: "code-optimization",
      name: "Code Optimization",
      file: "code-optimization.svg",
    },
    { slug: "code", name: "Code", file: "code.svg" },
    {
      slug: "cognitive-search",
      name: "Cognitive Search",
      file: "cognitive-search.svg",
    },
    {
      slug: "cognitive-services-decisions",
      name: "Cognitive Services Decisions",
      file: "cognitive-services-decisions.svg",
    },
    {
      slug: "cognitive-services",
      name: "Cognitive Services",
      file: "cognitive-services.svg",
    },
    {
      slug: "collaborative-service",
      name: "Collaborative Service",
      file: "collaborative-service.svg",
    },
    { slug: "commit", name: "Commit", file: "commit.svg" },
    {
      slug: "community-images",
      name: "Community Images",
      file: "community-images.svg",
    },
    {
      slug: "compliance-center",
      name: "Compliance Center",
      file: "compliance-center.svg",
    },
    { slug: "compliance", name: "Compliance", file: "compliance.svg" },
    { slug: "compute-fleet", name: "Compute Fleet", file: "compute-fleet.svg" },
    {
      slug: "computer-vision",
      name: "Computer Vision",
      file: "computer-vision.svg",
    },
    {
      slug: "conditional-access",
      name: "Conditional Access",
      file: "conditional-access.svg",
    },
    {
      slug: "confidential-ledgers",
      name: "Confidential Ledgers",
      file: "confidential-ledgers.svg",
    },
    {
      slug: "connected-cache",
      name: "Connected Cache",
      file: "connected-cache.svg",
    },
    {
      slug: "connected-vehicle-platform",
      name: "Connected Vehicle Platform",
      file: "connected-vehicle-platform.svg",
    },
    { slug: "connections", name: "Connections", file: "connections.svg" },
    { slug: "consortium", name: "Consortium", file: "consortium.svg" },
    {
      slug: "container-apps-environments",
      name: "Container Apps Environments",
      file: "container-apps-environments.svg",
    },
    {
      slug: "container-instances",
      name: "Container Instances",
      file: "container-instances.svg",
    },
    {
      slug: "container-registries",
      name: "Container Registries",
      file: "container-registries.svg",
    },
    {
      slug: "container-services-deprecated",
      name: "Container Services (Deprecated)",
      file: "container-services-deprecated.svg",
    },
    {
      slug: "content-moderators",
      name: "Content Moderators",
      file: "content-moderators.svg",
    },
    {
      slug: "content-safety",
      name: "Content Safety",
      file: "content-safety.svg",
    },
    {
      slug: "controls-horizontal",
      name: "Controls Horizontal",
      file: "controls-horizontal.svg",
    },
    { slug: "controls", name: "Controls", file: "controls.svg" },
    { slug: "cost-alerts", name: "Cost Alerts", file: "cost-alerts.svg" },
    { slug: "cost-analysis", name: "Cost Analysis", file: "cost-analysis.svg" },
    { slug: "cost-budgets", name: "Cost Budgets", file: "cost-budgets.svg" },
    { slug: "cost-export", name: "Cost Export", file: "cost-export.svg" },
    {
      slug: "cost-management-and-billing",
      name: "Cost Management and Billing",
      file: "cost-management-and-billing.svg",
    },
    {
      slug: "cost-management",
      name: "Cost Management",
      file: "cost-management.svg",
    },
    { slug: "counter", name: "Counter", file: "counter.svg" },
    { slug: "cubes", name: "Cubes", file: "cubes.svg" },
    {
      slug: "custom-ip-prefix",
      name: "Custom IP Prefix",
      file: "custom-ip-prefix.svg",
    },
    { slug: "custom-vision", name: "Custom Vision", file: "custom-vision.svg" },
    {
      slug: "customer-lockbox-for-microsoft-azure",
      name: "Customer Lockbox for Microsoft Azure",
      file: "customer-lockbox-for-microsoft-azure.svg",
    },
    { slug: "dashboard-hub", name: "Dashboard Hub", file: "dashboard-hub.svg" },
    { slug: "dashboard", name: "Dashboard", file: "dashboard.svg" },
    { slug: "data-box", name: "Data Box", file: "data-box.svg" },
    {
      slug: "data-collection-rules",
      name: "Data Collection Rules",
      file: "data-collection-rules.svg",
    },
    {
      slug: "data-factories",
      name: "Data Factories",
      file: "data-factories.svg",
    },
    {
      slug: "data-lake-analytics",
      name: "Data Lake Analytics",
      file: "data-lake-analytics.svg",
    },
    {
      slug: "data-lake-storage-gen1",
      name: "Data Lake Storage Gen1",
      file: "data-lake-storage-gen1.svg",
    },
    {
      slug: "data-lake-store-gen1",
      name: "Data Lake Store Gen1",
      file: "data-lake-store-gen1.svg",
    },
    {
      slug: "data-share-invitations",
      name: "Data Share Invitations",
      file: "data-share-invitations.svg",
    },
    { slug: "data-shares", name: "Data Shares", file: "data-shares.svg" },
    {
      slug: "data-virtualization",
      name: "Data Virtualization",
      file: "data-virtualization.svg",
    },
    {
      slug: "database-instance-for-sap",
      name: "Database Instance For SAP",
      file: "database-instance-for-sap.svg",
    },
    {
      slug: "ddos-custom-policy",
      name: "DDoS Custom Policy",
      file: "ddos-custom-policy.svg",
    },
    {
      slug: "ddos-protection-plans",
      name: "DDoS Protection Plans",
      file: "ddos-protection-plans.svg",
    },
    { slug: "dedicated-hsm", name: "Dedicated HSM", file: "dedicated-hsm.svg" },
    {
      slug: "defender-cm-local-manager",
      name: "Defender CM Local Manager",
      file: "defender-cm-local-manager.svg",
    },
    {
      slug: "defender-dcs-controller",
      name: "Defender DCS Controller",
      file: "defender-dcs-controller.svg",
    },
    {
      slug: "defender-distributer-control-system",
      name: "Defender Distributer Control System",
      file: "defender-distributer-control-system.svg",
    },
    {
      slug: "defender-engineering-station",
      name: "Defender Engineering Station",
      file: "defender-engineering-station.svg",
    },
    {
      slug: "defender-external-management",
      name: "Defender External Management",
      file: "defender-external-management.svg",
    },
    {
      slug: "defender-freezer-monitor",
      name: "Defender Freezer Monitor",
      file: "defender-freezer-monitor.svg",
    },
    {
      slug: "defender-historian",
      name: "Defender Historian",
      file: "defender-historian.svg",
    },
    { slug: "defender-hmi", name: "Defender HMI", file: "defender-hmi.svg" },
    {
      slug: "defender-industrial-packaging-system",
      name: "Defender Industrial Packaging System",
      file: "defender-industrial-packaging-system.svg",
    },
    {
      slug: "defender-industrial-printer",
      name: "Defender Industrial Printer",
      file: "defender-industrial-printer.svg",
    },
    {
      slug: "defender-industrial-robot",
      name: "Defender Industrial Robot",
      file: "defender-industrial-robot.svg",
    },
    {
      slug: "defender-industrial-scale-system",
      name: "Defender Industrial Scale System",
      file: "defender-industrial-scale-system.svg",
    },
    {
      slug: "defender-marquee",
      name: "Defender Marquee",
      file: "defender-marquee.svg",
    },
    {
      slug: "defender-meter",
      name: "Defender Meter",
      file: "defender-meter.svg",
    },
    { slug: "defender-plc", name: "Defender PLC", file: "defender-plc.svg" },
    {
      slug: "defender-pneumatic-device",
      name: "Defender Pneumatic Device",
      file: "defender-pneumatic-device.svg",
    },
    {
      slug: "defender-programable-board",
      name: "Defender Programable Board",
      file: "defender-programable-board.svg",
    },
    {
      slug: "defender-relay",
      name: "Defender Relay",
      file: "defender-relay.svg",
    },
    {
      slug: "defender-robot-controller",
      name: "Defender Robot Controller",
      file: "defender-robot-controller.svg",
    },
    { slug: "defender-rtu", name: "Defender RTU", file: "defender-rtu.svg" },
    {
      slug: "defender-sensor",
      name: "Defender Sensor",
      file: "defender-sensor.svg",
    },
    { slug: "defender-slot", name: "Defender Slot", file: "defender-slot.svg" },
    {
      slug: "defender-web-guiding-system",
      name: "Defender Web Guiding System",
      file: "defender-web-guiding-system.svg",
    },
    { slug: "detonation", name: "Detonation", file: "detonation.svg" },
    { slug: "dev-console", name: "Dev Console", file: "dev-console.svg" },
    {
      slug: "device-compliance",
      name: "Device Compliance",
      file: "device-compliance.svg",
    },
    {
      slug: "device-configuration",
      name: "Device Configuration",
      file: "device-configuration.svg",
    },
    {
      slug: "device-enrollment",
      name: "Device Enrollment",
      file: "device-enrollment.svg",
    },
    {
      slug: "device-provisioning-services",
      name: "Device Provisioning Services",
      file: "device-provisioning-services.svg",
    },
    {
      slug: "device-security-apple",
      name: "Device Security Apple",
      file: "device-security-apple.svg",
    },
    {
      slug: "device-security-google",
      name: "Device Security Google",
      file: "device-security-google.svg",
    },
    {
      slug: "device-security-windows",
      name: "Device Security Windows",
      file: "device-security-windows.svg",
    },
    {
      slug: "device-update-iot-hub",
      name: "Device Update IoT Hub",
      file: "device-update-iot-hub.svg",
    },
    { slug: "devices", name: "Devices", file: "devices.svg" },
    {
      slug: "devops-starter",
      name: "DevOps Starter",
      file: "devops-starter.svg",
    },
    { slug: "devtest-labs", name: "DevTest Labs", file: "devtest-labs.svg" },
    {
      slug: "diagnostics-settings",
      name: "Diagnostics Settings",
      file: "diagnostics-settings.svg",
    },
    { slug: "digital-twins", name: "Digital Twins", file: "digital-twins.svg" },
    {
      slug: "disconnected-operations",
      name: "Disconnected Operations",
      file: "disconnected-operations.svg",
    },
    {
      slug: "disk-encryption-sets",
      name: "Disk Encryption Sets",
      file: "disk-encryption-sets.svg",
    },
    { slug: "disk-pool", name: "Disk Pool", file: "disk-pool.svg" },
    {
      slug: "disks-classic",
      name: "Disks (Classic)",
      file: "disks-classic.svg",
    },
    {
      slug: "disks-snapshots",
      name: "Disks Snapshots",
      file: "disks-snapshots.svg",
    },
    { slug: "disks", name: "Disks", file: "disks.svg" },
    {
      slug: "dns-multistack",
      name: "DNS Multistack",
      file: "dns-multistack.svg",
    },
    {
      slug: "dns-private-resolver",
      name: "DNS Private Resolver",
      file: "dns-private-resolver.svg",
    },
    {
      slug: "dns-security-policy",
      name: "DNS Security Policy",
      file: "dns-security-policy.svg",
    },
    { slug: "dns-zones", name: "DNS Zones", file: "dns-zones.svg" },
    { slug: "download", name: "Download", file: "download.svg" },
    { slug: "ebooks", name: "eBooks", file: "ebooks.svg" },
    { slug: "edge-actions", name: "Edge Actions", file: "edge-actions.svg" },
    {
      slug: "edge-management",
      name: "Edge Management",
      file: "edge-management.svg",
    },
    {
      slug: "edge-storage-accelerator",
      name: "Edge Storage Accelerator",
      file: "edge-storage-accelerator.svg",
    },
    { slug: "education", name: "Education", file: "education.svg" },
    {
      slug: "elastic-job-agents",
      name: "Elastic Job Agents",
      file: "elastic-job-agents.svg",
    },
    { slug: "elastic-san", name: "Elastic SAN", file: "elastic-san.svg" },
    {
      slug: "endpoint-analytics",
      name: "Endpoint Analytics",
      file: "endpoint-analytics.svg",
    },
    {
      slug: "engage-center-connect",
      name: "Engage Center Connect",
      file: "engage-center-connect.svg",
    },
    {
      slug: "enterprise-applications",
      name: "Enterprise Applications",
      file: "enterprise-applications.svg",
    },
    {
      slug: "entra-connect-health",
      name: "Entra Connect Health",
      file: "entra-connect-health.svg",
    },
    {
      slug: "entra-connect-sync",
      name: "Entra Connect Sync",
      file: "entra-connect-sync.svg",
    },
    { slug: "entra-connect", name: "Entra Connect", file: "entra-connect.svg" },
    {
      slug: "entra-domain-services",
      name: "Entra Domain Services",
      file: "entra-domain-services.svg",
    },
    {
      slug: "entra-global-secure-access",
      name: "Entra Global Secure Access",
      file: "entra-global-secure-access.svg",
    },
    {
      slug: "entra-id-protection",
      name: "Entra ID Protection",
      file: "entra-id-protection.svg",
    },
    {
      slug: "entra-identity-custom-roles",
      name: "Entra Identity Custom Roles",
      file: "entra-identity-custom-roles.svg",
    },
    {
      slug: "entra-identity-licenses",
      name: "Entra Identity Licenses",
      file: "entra-identity-licenses.svg",
    },
    {
      slug: "entra-identity-risky-signins",
      name: "Entra Identity Risky Signins",
      file: "entra-identity-risky-signins.svg",
    },
    {
      slug: "entra-identity-risky-users",
      name: "Entra Identity Risky Users",
      file: "entra-identity-risky-users.svg",
    },
    {
      slug: "entra-identity-roles-and-administrators",
      name: "Entra Identity Roles and Administrators",
      file: "entra-identity-roles-and-administrators.svg",
    },
    {
      slug: "entra-internet-access",
      name: "Entra Internet Access",
      file: "entra-internet-access.svg",
    },
    {
      slug: "entra-managed-identities",
      name: "Entra Managed Identities",
      file: "entra-managed-identities.svg",
    },
    {
      slug: "entra-private-access",
      name: "Entra Private Access",
      file: "entra-private-access.svg",
    },
    {
      slug: "entra-privleged-identity-management",
      name: "Entra Privleged Identity Management",
      file: "entra-privleged-identity-management.svg",
    },
    {
      slug: "entra-verified-id",
      name: "Entra Verified ID",
      file: "entra-verified-id.svg",
    },
    { slug: "error", name: "Error", file: "error.svg" },
    {
      slug: "event-grid-domains",
      name: "Event Grid Domains",
      file: "event-grid-domains.svg",
    },
    {
      slug: "event-grid-subscriptions",
      name: "Event Grid Subscriptions",
      file: "event-grid-subscriptions.svg",
    },
    {
      slug: "event-grid-topics",
      name: "Event Grid Topics",
      file: "event-grid-topics.svg",
    },
    {
      slug: "event-hub-clusters",
      name: "Event Hub Clusters",
      file: "event-hub-clusters.svg",
    },
    { slug: "event-hubs", name: "Event Hubs", file: "event-hubs.svg" },
    {
      slug: "exchange-access",
      name: "Exchange Access",
      file: "exchange-access.svg",
    },
    {
      slug: "exchange-on-premises-access",
      name: "Exchange On Premises Access",
      file: "exchange-on-premises-access.svg",
    },
    {
      slug: "express-route-traffic-collector",
      name: "Express Route Traffic Collector",
      file: "express-route-traffic-collector.svg",
    },
    {
      slug: "expressroute-circuits",
      name: "ExpressRoute Circuits",
      file: "expressroute-circuits.svg",
    },
    {
      slug: "expressroute-direct",
      name: "ExpressRoute Direct",
      file: "expressroute-direct.svg",
    },
    {
      slug: "extendedsecurityupdates",
      name: "ExtendedSecurityUpdates",
      file: "extendedsecurityupdates.svg",
    },
    { slug: "extensions", name: "Extensions", file: "extensions.svg" },
    {
      slug: "external-id-modified",
      name: "external id modified",
      file: "external-id-modified.svg",
    },
    { slug: "external-id", name: "external id", file: "external-id.svg" },
    {
      slug: "external-identities",
      name: "External Identities",
      file: "external-identities.svg",
    },
    { slug: "face-apis", name: "Face APIs", file: "face-apis.svg" },
    {
      slug: "feature-previews",
      name: "Feature Previews",
      file: "feature-previews.svg",
    },
    { slug: "fhir-service", name: "FHIR Service", file: "fhir-service.svg" },
    { slug: "fiji", name: "Fiji", file: "fiji.svg" },
    { slug: "file", name: "File", file: "file.svg" },
    { slug: "files", name: "Files", file: "files.svg" },
    { slug: "firewalls", name: "Firewalls", file: "firewalls.svg" },
    { slug: "folder-blank", name: "Folder Blank", file: "folder-blank.svg" },
    {
      slug: "folder-website",
      name: "Folder Website",
      file: "folder-website.svg",
    },
    {
      slug: "form-recognizers",
      name: "Form Recognizers",
      file: "form-recognizers.svg",
    },
    {
      slug: "foundry-agent-service",
      name: "Foundry Agent Service",
      file: "foundry-agent-service.svg",
    },
    {
      slug: "foundry-application",
      name: "Foundry Application",
      file: "foundry-application.svg",
    },
    {
      slug: "foundry-control-plane",
      name: "Foundry Control Plane",
      file: "foundry-control-plane.svg",
    },
    { slug: "foundry-labs", name: "Foundry Labs", file: "foundry-labs.svg" },
    { slug: "foundry-local", name: "Foundry Local", file: "foundry-local.svg" },
    {
      slug: "foundry-models",
      name: "Foundry Models",
      file: "foundry-models.svg",
    },
    {
      slug: "foundry-project",
      name: "Foundry Project",
      file: "foundry-project.svg",
    },
    { slug: "frd-qa", name: "FRD QA", file: "frd-qa.svg" },
    { slug: "free-services", name: "Free Services", file: "free-services.svg" },
    {
      slug: "front-door-and-cdn-profiles",
      name: "Front Door and CDN Profiles",
      file: "front-door-and-cdn-profiles.svg",
    },
    { slug: "ftp", name: "FTP", file: "ftp.svg" },
    { slug: "function-apps", name: "Function Apps", file: "function-apps.svg" },
    { slug: "gear", name: "Gear", file: "gear.svg" },
    {
      slug: "genomics-accounts",
      name: "Genomics Accounts",
      file: "genomics-accounts.svg",
    },
    { slug: "genomics", name: "Genomics", file: "genomics.svg" },
    { slug: "globe-error", name: "Globe Error", file: "globe-error.svg" },
    { slug: "globe-success", name: "Globe Success", file: "globe-success.svg" },
    { slug: "globe-warning", name: "Globe Warning", file: "globe-warning.svg" },
    { slug: "groups", name: "Groups", file: "groups.svg" },
    { slug: "guide", name: "Guide", file: "guide.svg" },
    {
      slug: "hd-insight-clusters",
      name: "HD Insight Clusters",
      file: "hd-insight-clusters.svg",
    },
    {
      slug: "hdi-aks-cluster",
      name: "HDI AKS Cluster",
      file: "hdi-aks-cluster.svg",
    },
    { slug: "heart", name: "Heart", file: "heart.svg" },
    {
      slug: "help-and-support",
      name: "Help and Support",
      file: "help-and-support.svg",
    },
    { slug: "host-groups", name: "Host Groups", file: "host-groups.svg" },
    { slug: "host-pools", name: "Host Pools", file: "host-pools.svg" },
    { slug: "hosts", name: "Hosts", file: "hosts.svg" },
    {
      slug: "hybrid-connectivity-hub",
      name: "Hybrid Connectivity Hub",
      file: "hybrid-connectivity-hub.svg",
    },
    {
      slug: "icm-troubleshooting",
      name: "IcM Troubleshooting",
      file: "icm-troubleshooting.svg",
    },
    {
      slug: "identity-governance",
      name: "Identity Governance",
      file: "identity-governance.svg",
    },
    {
      slug: "identity-secure-score",
      name: "Identity Secure Score",
      file: "identity-secure-score.svg",
    },
    {
      slug: "image-definitions",
      name: "Image Definitions",
      file: "image-definitions.svg",
    },
    {
      slug: "image-templates",
      name: "Image Templates",
      file: "image-templates.svg",
    },
    {
      slug: "image-versions",
      name: "Image Versions",
      file: "image-versions.svg",
    },
    { slug: "image", name: "Image", file: "image.svg" },
    { slug: "images", name: "Images", file: "images.svg" },
    {
      slug: "immersive-readers",
      name: "Immersive Readers",
      file: "immersive-readers.svg",
    },
    {
      slug: "import-export-jobs",
      name: "Import Export Jobs",
      file: "import-export-jobs.svg",
    },
    {
      slug: "industrial-iot",
      name: "Industrial IoT",
      file: "industrial-iot.svg",
    },
    { slug: "information", name: "Information", file: "information.svg" },
    { slug: "input-output", name: "Input Output", file: "input-output.svg" },
    {
      slug: "instance-pools",
      name: "Instance Pools",
      file: "instance-pools.svg",
    },
    {
      slug: "integration-accounts",
      name: "Integration Accounts",
      file: "integration-accounts.svg",
    },
    {
      slug: "integration-environments",
      name: "Integration Environments",
      file: "integration-environments.svg",
    },
    {
      slug: "integration-service-environments",
      name: "Integration Service Environments",
      file: "integration-service-environments.svg",
    },
    {
      slug: "internet-analyzer-profiles",
      name: "Internet Analyzer Profiles",
      file: "internet-analyzer-profiles.svg",
    },
    {
      slug: "intune-app-protection",
      name: "Intune App Protection",
      file: "intune-app-protection.svg",
    },
    {
      slug: "intune-for-education",
      name: "Intune For Education",
      file: "intune-for-education.svg",
    },
    { slug: "intune-trends", name: "Intune Trends", file: "intune-trends.svg" },
    { slug: "intune", name: "Intune", file: "intune.svg" },
    {
      slug: "iot-central-applications",
      name: "IoT Central Applications",
      file: "iot-central-applications.svg",
    },
    { slug: "iot-edge", name: "IoT Edge", file: "iot-edge.svg" },
    { slug: "iot-hub", name: "IoT Hub", file: "iot-hub.svg" },
    {
      slug: "ip-address-manager",
      name: "IP Address manager",
      file: "ip-address-manager.svg",
    },
    { slug: "ip-groups", name: "IP Groups", file: "ip-groups.svg" },
    { slug: "journey-hub", name: "Journey Hub", file: "journey-hub.svg" },
    { slug: "key-vaults", name: "Key Vaults", file: "key-vaults.svg" },
    { slug: "keys", name: "Keys", file: "keys.svg" },
    {
      slug: "kubernetes-fleet-manager",
      name: "Kubernetes Fleet Manager",
      file: "kubernetes-fleet-manager.svg",
    },
    {
      slug: "kubernetes-hub",
      name: "Kubernetes Hub",
      file: "kubernetes-hub.svg",
    },
    {
      slug: "kubernetes-services",
      name: "Kubernetes Services",
      file: "kubernetes-services.svg",
    },
    { slug: "lab-accounts", name: "Lab Accounts", file: "lab-accounts.svg" },
    { slug: "lab-services", name: "Lab Services", file: "lab-services.svg" },
    { slug: "landing-zone", name: "Landing Zone", file: "landing-zone.svg" },
    {
      slug: "language-understanding",
      name: "Language Understanding",
      file: "language-understanding.svg",
    },
    { slug: "language", name: "Language", file: "language.svg" },
    { slug: "launch-portal", name: "Launch Portal", file: "launch-portal.svg" },
    { slug: "learn", name: "Learn", file: "learn.svg" },
    {
      slug: "load-balancer-hub-029029174",
      name: "Load Balancer Hub",
      file: "load-balancer-hub-029029174.svg",
    },
    {
      slug: "load-balancer-hub",
      name: "Load Balancer Hub",
      file: "load-balancer-hub.svg",
    },
    {
      slug: "load-balancers",
      name: "Load Balancers",
      file: "load-balancers.svg",
    },
    { slug: "load-test", name: "Load Test", file: "load-test.svg" },
    { slug: "load-testing", name: "Load Testing", file: "load-testing.svg" },
    {
      slug: "local-network-gateways",
      name: "Local Network Gateways",
      file: "local-network-gateways.svg",
    },
    { slug: "location", name: "Location", file: "location.svg" },
    {
      slug: "log-analytics-query-pack",
      name: "Log Analytics Query Pack",
      file: "log-analytics-query-pack.svg",
    },
    {
      slug: "log-analytics-workspaces",
      name: "Log Analytics Workspaces",
      file: "log-analytics-workspaces.svg",
    },
    { slug: "log-streaming", name: "Log Streaming", file: "log-streaming.svg" },
    {
      slug: "logic-apps-custom-connector",
      name: "Logic Apps Custom Connector",
      file: "logic-apps-custom-connector.svg",
    },
    {
      slug: "logic-apps-template",
      name: "Logic Apps Template",
      file: "logic-apps-template.svg",
    },
    { slug: "logic-apps", name: "Logic Apps", file: "logic-apps.svg" },
    {
      slug: "machine-learning-studio-classic-web-services",
      name: "Machine Learning Studio (Classic) Web Services",
      file: "machine-learning-studio-classic-web-services.svg",
    },
    {
      slug: "machine-learning-studio-web-service-plans",
      name: "Machine Learning Studio Web Service Plans",
      file: "machine-learning-studio-web-service-plans.svg",
    },
    {
      slug: "machine-learning-studio-workspaces",
      name: "Machine Learning Studio Workspaces",
      file: "machine-learning-studio-workspaces.svg",
    },
    {
      slug: "machine-learning",
      name: "Machine Learning",
      file: "machine-learning.svg",
    },
    {
      slug: "machinesazurearc",
      name: "MachinesAzureArc",
      file: "machinesazurearc.svg",
    },
    {
      slug: "maintenance-configuration",
      name: "Maintenance Configuration",
      file: "maintenance-configuration.svg",
    },
    {
      slug: "managed-applications-center",
      name: "Managed Applications Center",
      file: "managed-applications-center.svg",
    },
    {
      slug: "managed-database",
      name: "Managed Database",
      file: "managed-database.svg",
    },
    {
      slug: "managed-desktop",
      name: "Managed Desktop",
      file: "managed-desktop.svg",
    },
    {
      slug: "managed-devops-pools",
      name: "Managed DevOps Pools",
      file: "managed-devops-pools.svg",
    },
    {
      slug: "managed-file-shares",
      name: "Managed File Shares",
      file: "managed-file-shares.svg",
    },
    {
      slug: "managed-identities",
      name: "Managed Identities",
      file: "managed-identities.svg",
    },
    {
      slug: "managed-instance-apache-cassandra",
      name: "Managed Instance Apache Cassandra",
      file: "managed-instance-apache-cassandra.svg",
    },
    {
      slug: "managed-service-fabric",
      name: "Managed Service Fabric",
      file: "managed-service-fabric.svg",
    },
    {
      slug: "management-groups",
      name: "Management Groups",
      file: "management-groups.svg",
    },
    {
      slug: "management-portal",
      name: "Management Portal",
      file: "management-portal.svg",
    },
    {
      slug: "marketplace-management",
      name: "Marketplace Management",
      file: "marketplace-management.svg",
    },
    { slug: "gcp-marketplace", name: "Marketplace", file: "marketplace.svg" },
    { slug: "media-file", name: "Media File", file: "media-file.svg" },
    { slug: "media", name: "Media", file: "media.svg" },
    {
      slug: "medtech-service",
      name: "MedTech Service",
      file: "medtech-service.svg",
    },
    {
      slug: "mesh-applications",
      name: "Mesh Applications",
      file: "mesh-applications.svg",
    },
    {
      slug: "metrics-advisor",
      name: "Metrics Advisor",
      file: "metrics-advisor.svg",
    },
    { slug: "metrics", name: "Metrics", file: "metrics.svg" },
    {
      slug: "microsoft-defender-easm",
      name: "Microsoft Defender EASM",
      file: "microsoft-defender-easm.svg",
    },
    {
      slug: "microsoft-defender-for-cloud",
      name: "Microsoft Defender for Cloud",
      file: "microsoft-defender-for-cloud.svg",
    },
    {
      slug: "microsoft-defender-for-iot",
      name: "Microsoft Defender for IoT",
      file: "microsoft-defender-for-iot.svg",
    },
    {
      slug: "microsoft-dev-box",
      name: "Microsoft Dev Box",
      file: "microsoft-dev-box.svg",
    },
    {
      slug: "microsoft-discovery",
      name: "Microsoft Discovery",
      file: "microsoft-discovery.svg",
    },
    { slug: "mindaro", name: "Mindaro", file: "mindaro.svg" },
    {
      slug: "mission-landing-zone",
      name: "Mission Landing Zone",
      file: "mission-landing-zone.svg",
    },
    {
      slug: "mobile-engagement",
      name: "Mobile Engagement",
      file: "mobile-engagement.svg",
    },
    {
      slug: "mobile-networks",
      name: "Mobile Networks",
      file: "mobile-networks.svg",
    },
    { slug: "mobile", name: "Mobile", file: "mobile.svg" },
    {
      slug: "modular-data-center",
      name: "Modular Data Center",
      file: "modular-data-center.svg",
    },
    { slug: "module", name: "Module", file: "module.svg" },
    {
      slug: "monitor-health-models",
      name: "Monitor Health Models",
      file: "monitor-health-models.svg",
    },
    { slug: "monitor", name: "Monitor", file: "monitor.svg" },
    {
      slug: "multi-factor-authentication",
      name: "Multi Factor Authentication",
      file: "multi-factor-authentication.svg",
    },
    { slug: "multi-tenancy", name: "Multi Tenancy", file: "multi-tenancy.svg" },
    {
      slug: "multifactor-authentication",
      name: "Multifactor Authentication",
      file: "multifactor-authentication.svg",
    },
    { slug: "my-customers", name: "My Customers", file: "my-customers.svg" },
    { slug: "nat", name: "NAT", file: "nat.svg" },
    {
      slug: "network-foundation-hub",
      name: "Network Foundation Hub",
      file: "network-foundation-hub.svg",
    },
    {
      slug: "network-interfaces",
      name: "Network Interfaces",
      file: "network-interfaces.svg",
    },
    {
      slug: "network-managers",
      name: "Network Managers",
      file: "network-managers.svg",
    },
    {
      slug: "network-security-groups",
      name: "Network Security Groups",
      file: "network-security-groups.svg",
    },
    {
      slug: "network-security-hub",
      name: "Network Security Hub",
      file: "network-security-hub.svg",
    },
    {
      slug: "network-security-perimeters",
      name: "Network Security Perimeters",
      file: "network-security-perimeters.svg",
    },
    {
      slug: "network-watcher",
      name: "Network Watcher",
      file: "network-watcher.svg",
    },
    {
      slug: "notification-hub-namespaces",
      name: "Notification Hub Namespaces",
      file: "notification-hub-namespaces.svg",
    },
    {
      slug: "notification-hubs",
      name: "Notification Hubs",
      file: "notification-hubs.svg",
    },
    {
      slug: "on-premises-data-gateways",
      name: "On Premises Data Gateways",
      file: "on-premises-data-gateways.svg",
    },
    {
      slug: "open-supply-chain-platform",
      name: "Open Supply Chain Platform",
      file: "open-supply-chain-platform.svg",
    },
    {
      slug: "operation-log-classic",
      name: "Operation Log (Classic)",
      file: "operation-log-classic.svg",
    },
    {
      slug: "oracle-database",
      name: "Oracle Database",
      file: "oracle-database.svg",
    },
    {
      slug: "os-images-classic",
      name: "OS Images (Classic)",
      file: "os-images-classic.svg",
    },
    { slug: "osconfig", name: "OSConfig", file: "osconfig.svg" },
    {
      slug: "outbound-connection",
      name: "Outbound Connection",
      file: "outbound-connection.svg",
    },
    {
      slug: "partner-namespace",
      name: "Partner Namespace",
      file: "partner-namespace.svg",
    },
    {
      slug: "partner-registration",
      name: "Partner Registration",
      file: "partner-registration.svg",
    },
    { slug: "partner-topic", name: "Partner Topic", file: "partner-topic.svg" },
    {
      slug: "peering-service",
      name: "Peering Service",
      file: "peering-service.svg",
    },
    { slug: "peerings", name: "Peerings", file: "peerings.svg" },
    { slug: "personalizers", name: "Personalizers", file: "personalizers.svg" },
    {
      slug: "planetary-computer-pro",
      name: "Planetary Computer Pro",
      file: "planetary-computer-pro.svg",
    },
    { slug: "policy", name: "Policy", file: "policy.svg" },
    {
      slug: "power-bi-embedded",
      name: "Power BI Embedded",
      file: "power-bi-embedded.svg",
    },
    {
      slug: "power-platform",
      name: "Power Platform",
      file: "power-platform.svg",
    },
    { slug: "power-up", name: "Power Up", file: "power-up.svg" },
    { slug: "power", name: "Power", file: "power.svg" },
    { slug: "powershell", name: "Powershell", file: "powershell.svg" },
    {
      slug: "preview-features",
      name: "Preview Features",
      file: "preview-features.svg",
    },
    {
      slug: "private-endpoints",
      name: "Private Endpoints",
      file: "private-endpoints.svg",
    },
    {
      slug: "private-link-service",
      name: "Private Link Service",
      file: "private-link-service.svg",
    },
    {
      slug: "private-link-services",
      name: "Private Link Services",
      file: "private-link-services.svg",
    },
    { slug: "private-link", name: "Private Link", file: "private-link.svg" },
    {
      slug: "process-explorer",
      name: "Process Explorer",
      file: "process-explorer.svg",
    },
    {
      slug: "production-ready-database",
      name: "Production Ready Database",
      file: "production-ready-database.svg",
    },
    { slug: "promethus", name: "promethus", file: "promethus.svg" },
    {
      slug: "proximity-placement-groups",
      name: "Proximity Placement Groups",
      file: "proximity-placement-groups.svg",
    },
    {
      slug: "public-ip-addresses-classic",
      name: "Public IP Addresses (Classic)",
      file: "public-ip-addresses-classic.svg",
    },
    {
      slug: "public-ip-addresses",
      name: "Public IP Addresses",
      file: "public-ip-addresses.svg",
    },
    {
      slug: "public-ip-prefixes",
      name: "Public IP Prefixes",
      file: "public-ip-prefixes.svg",
    },
    { slug: "pubsub", name: "pubsub", file: "pubsub.svg" },
    { slug: "qna-makers", name: "QnA Makers", file: "qna-makers.svg" },
    {
      slug: "quickstart-center",
      name: "Quickstart Center",
      file: "quickstart-center.svg",
    },
    { slug: "recent", name: "Recent", file: "recent.svg" },
    {
      slug: "recovery-services-vaults",
      name: "Recovery Services Vaults",
      file: "recovery-services-vaults.svg",
    },
    {
      slug: "region-management",
      name: "Region Management",
      file: "region-management.svg",
    },
    { slug: "relays", name: "Relays", file: "relays.svg" },
    {
      slug: "remote-rendering",
      name: "Remote Rendering",
      file: "remote-rendering.svg",
    },
    { slug: "reservations", name: "Reservations", file: "reservations.svg" },
    {
      slug: "reserved-capacity",
      name: "Reserved Capacity",
      file: "reserved-capacity.svg",
    },
    {
      slug: "reserved-ip-addresses-classic",
      name: "Reserved IP Addresses (Classic)",
      file: "reserved-ip-addresses-classic.svg",
    },
    { slug: "resiliency", name: "Resiliency", file: "resiliency.svg" },
    {
      slug: "azure-resource-explorer",
      name: "Resource Explorer",
      file: "resource-explorer.svg",
    },
    {
      slug: "resource-graph-explorer",
      name: "Resource Graph Explorer",
      file: "resource-graph-explorer.svg",
    },
    {
      slug: "resource-group-list",
      name: "Resource Group List",
      file: "resource-group-list.svg",
    },
    {
      slug: "resource-groups",
      name: "Resource Groups",
      file: "resource-groups.svg",
    },
    {
      slug: "resource-guard",
      name: "Resource Guard",
      file: "resource-guard.svg",
    },
    {
      slug: "resource-linked",
      name: "Resource Linked",
      file: "resource-linked.svg",
    },
    {
      slug: "resource-management-private-link",
      name: "Resource Management Private Link",
      file: "resource-management-private-link.svg",
    },
    {
      slug: "resource-mover",
      name: "Resource Mover",
      file: "resource-mover.svg",
    },
    {
      slug: "resources-provider",
      name: "Resources Provider",
      file: "resources-provider.svg",
    },
    {
      slug: "restore-points-collections",
      name: "Restore Points Collections",
      file: "restore-points-collections.svg",
    },
    {
      slug: "restore-points",
      name: "Restore Points",
      file: "restore-points.svg",
    },
    { slug: "route-filters", name: "Route Filters", file: "route-filters.svg" },
    { slug: "route-tables", name: "Route Tables", file: "route-tables.svg" },
    { slug: "rtos", name: "RTOS", file: "rtos.svg" },
    {
      slug: "azure-savings-plans",
      name: "Savings Plans",
      file: "savings-plans.svg",
    },
    {
      slug: "scheduled-actions",
      name: "Scheduled Actions",
      file: "scheduled-actions.svg",
    },
    {
      slug: "scheduler-job-collections",
      name: "Scheduler Job Collections",
      file: "scheduler-job-collections.svg",
    },
    { slug: "scheduler", name: "Scheduler", file: "scheduler.svg" },
    {
      slug: "scvmm-management-servers",
      name: "SCVMM Management Servers",
      file: "scvmm-management-servers.svg",
    },
    { slug: "search-grid", name: "Search Grid", file: "search-grid.svg" },
    { slug: "search", name: "Search", file: "search.svg" },
    {
      slug: "security-baselines",
      name: "Security Baselines",
      file: "security-baselines.svg",
    },
    { slug: "security", name: "Security", file: "security.svg" },
    {
      slug: "sendgrid-accounts",
      name: "SendGrid Accounts",
      file: "sendgrid-accounts.svg",
    },
    { slug: "server-farm", name: "Server Farm", file: "server-farm.svg" },
    {
      slug: "serverless-search",
      name: "Serverless Search",
      file: "serverless-search.svg",
    },
    {
      slug: "service-catalog-mad",
      name: "Service Catalog MAD",
      file: "service-catalog-mad.svg",
    },
    {
      slug: "service-endpoint-policies",
      name: "Service Endpoint Policies",
      file: "service-endpoint-policies.svg",
    },
    {
      slug: "service-fabric-clusters",
      name: "Service Fabric Clusters",
      file: "service-fabric-clusters.svg",
    },
    {
      slug: "service-group-relationships",
      name: "Service Group Relationships",
      file: "service-group-relationships.svg",
    },
    {
      slug: "service-groups",
      name: "Service Groups",
      file: "service-groups.svg",
    },
    {
      slug: "service-health",
      name: "Service Health",
      file: "service-health.svg",
    },
    {
      slug: "service-providers",
      name: "Service Providers",
      file: "service-providers.svg",
    },
    {
      slug: "shared-image-galleries",
      name: "Shared Image Galleries",
      file: "shared-image-galleries.svg",
    },
    { slug: "signalr", name: "SignalR", file: "signalr.svg" },
    {
      slug: "software-as-a-service",
      name: "Software as a Service",
      file: "software-as-a-service.svg",
    },
    {
      slug: "software-updates",
      name: "Software Updates",
      file: "software-updates.svg",
    },
    { slug: "solutions", name: "Solutions", file: "solutions.svg" },
    { slug: "sonic-dash", name: "Sonic Dash", file: "sonic-dash.svg" },
    {
      slug: "spatial-anchor-accounts",
      name: "Spatial Anchor Accounts",
      file: "spatial-anchor-accounts.svg",
    },
    {
      slug: "speech-services",
      name: "Speech Services",
      file: "speech-services.svg",
    },
    { slug: "spot-vm", name: "Spot VM", file: "spot-vm.svg" },
    { slug: "spot-vmss", name: "Spot VMSS", file: "spot-vmss.svg" },
    {
      slug: "sql-data-warehouses",
      name: "SQL Data Warehouses",
      file: "sql-data-warehouses.svg",
    },
    {
      slug: "sql-database-fleet-manager",
      name: "SQL Database Fleet Manager",
      file: "sql-database-fleet-manager.svg",
    },
    { slug: "sql-database", name: "SQL Database", file: "sql-database.svg" },
    {
      slug: "sql-elastic-pools",
      name: "SQL Elastic Pools",
      file: "sql-elastic-pools.svg",
    },
    {
      slug: "sql-managed-instance",
      name: "SQL Managed Instance",
      file: "sql-managed-instance.svg",
    },
    {
      slug: "sql-server-registries",
      name: "SQL Server Registries",
      file: "sql-server-registries.svg",
    },
    { slug: "sql-server", name: "SQL Server", file: "sql-server.svg" },
    { slug: "ssd", name: "SSD", file: "ssd.svg" },
    { slug: "ssh-keys", name: "SSH Keys", file: "ssh-keys.svg" },
    {
      slug: "ssis-lift-and-shift-ir",
      name: "SSIS Lift And Shift IR",
      file: "ssis-lift-and-shift-ir.svg",
    },
    {
      slug: "stack-hci-premium",
      name: "Stack HCI Premium",
      file: "stack-hci-premium.svg",
    },
    { slug: "stage-maps", name: "Stage Maps", file: "stage-maps.svg" },
    { slug: "static-apps", name: "Static Apps", file: "static-apps.svg" },
    {
      slug: "storage-accounts-classic",
      name: "Storage Accounts (Classic)",
      file: "storage-accounts-classic.svg",
    },
    {
      slug: "storage-accounts",
      name: "Storage Accounts",
      file: "storage-accounts.svg",
    },
    {
      slug: "storage-actions",
      name: "Storage Actions",
      file: "storage-actions.svg",
    },
    {
      slug: "storage-azure-files",
      name: "Storage Azure Files",
      file: "storage-azure-files.svg",
    },
    {
      slug: "storage-container",
      name: "Storage Container",
      file: "storage-container.svg",
    },
    {
      slug: "storage-explorer",
      name: "Storage Explorer",
      file: "storage-explorer.svg",
    },
    {
      slug: "storage-functions",
      name: "Storage Functions",
      file: "storage-functions.svg",
    },
    { slug: "storage-hubs", name: "Storage Hubs", file: "storage-hubs.svg" },
    { slug: "storage-queue", name: "Storage Queue", file: "storage-queue.svg" },
    {
      slug: "storage-sync-services",
      name: "Storage Sync Services",
      file: "storage-sync-services.svg",
    },
    {
      slug: "storsimple-data-managers",
      name: "StorSimple Data Managers",
      file: "storsimple-data-managers.svg",
    },
    {
      slug: "storsimple-device-managers",
      name: "StorSimple Device Managers",
      file: "storsimple-device-managers.svg",
    },
    {
      slug: "stream-analytics-jobs",
      name: "Stream Analytics Jobs",
      file: "stream-analytics-jobs.svg",
    },
    { slug: "subnet", name: "Subnet", file: "subnet.svg" },
    { slug: "subscriptions", name: "Subscriptions", file: "subscriptions.svg" },
    { slug: "system-topic", name: "System Topic", file: "system-topic.svg" },
    { slug: "table", name: "Table", file: "table.svg" },
    { slug: "tag", name: "Tag", file: "tag.svg" },
    { slug: "tags", name: "Tags", file: "tags.svg" },
    {
      slug: "targets-management",
      name: "Targets Management",
      file: "targets-management.svg",
    },
    {
      slug: "template-specs",
      name: "Template Specs",
      file: "template-specs.svg",
    },
    { slug: "templates", name: "Templates", file: "templates.svg" },
    {
      slug: "tenant-properties",
      name: "Tenant Properties",
      file: "tenant-properties.svg",
    },
    { slug: "tenant-status", name: "Tenant Status", file: "tenant-status.svg" },
    { slug: "test-base", name: "Test Base", file: "test-base.svg" },
    {
      slug: "tfs-vc-repository",
      name: "TFS VC Repository",
      file: "tfs-vc-repository.svg",
    },
    {
      slug: "time-series-data-sets",
      name: "Time Series Data Sets",
      file: "time-series-data-sets.svg",
    },
    {
      slug: "time-series-insights-access-policies",
      name: "Time Series Insights Access Policies",
      file: "time-series-insights-access-policies.svg",
    },
    {
      slug: "time-series-insights-environments",
      name: "Time Series Insights Environments",
      file: "time-series-insights-environments.svg",
    },
    {
      slug: "time-series-insights-event-sources",
      name: "Time Series Insights Event Sources",
      file: "time-series-insights-event-sources.svg",
    },
    { slug: "toolbox", name: "Toolbox", file: "toolbox.svg" },
    {
      slug: "toolchain-orchestrator",
      name: "Toolchain Orchestrator",
      file: "toolchain-orchestrator.svg",
    },
    {
      slug: "traffic-manager-profiles",
      name: "Traffic Manager Profiles",
      file: "traffic-manager-profiles.svg",
    },
    {
      slug: "translator-text",
      name: "Translator Text",
      file: "translator-text.svg",
    },
    { slug: "troubleshoot", name: "Troubleshoot", file: "troubleshoot.svg" },
    {
      slug: "universal-print",
      name: "Universal Print",
      file: "universal-print.svg",
    },
    {
      slug: "update-management-center",
      name: "Update Management Center",
      file: "update-management-center.svg",
    },
    { slug: "user-privacy", name: "User Privacy", file: "user-privacy.svg" },
    { slug: "user-settings", name: "User Settings", file: "user-settings.svg" },
    {
      slug: "user-subscriptions",
      name: "User Subscriptions",
      file: "user-subscriptions.svg",
    },
    { slug: "users", name: "Users", file: "users.svg" },
    {
      slug: "verifiable-credentials",
      name: "Verifiable Credentials",
      file: "verifiable-credentials.svg",
    },
    {
      slug: "verification-as-a-service",
      name: "Verification As A Service",
      file: "verification-as-a-service.svg",
    },
    { slug: "versions", name: "Versions", file: "versions.svg" },
    {
      slug: "video-analyzers",
      name: "Video Analyzers",
      file: "video-analyzers.svg",
    },
    {
      slug: "virtual-clusters",
      name: "Virtual Clusters",
      file: "virtual-clusters.svg",
    },
    {
      slug: "virtual-instance-for-sap",
      name: "Virtual Instance for SAP",
      file: "virtual-instance-for-sap.svg",
    },
    {
      slug: "virtual-machine",
      name: "Virtual Machine",
      file: "virtual-machine.svg",
    },
    {
      slug: "virtual-machines-classic",
      name: "Virtual Machines (Classic)",
      file: "virtual-machines-classic.svg",
    },
    {
      slug: "virtual-network-gateways",
      name: "Virtual Network Gateways",
      file: "virtual-network-gateways.svg",
    },
    {
      slug: "virtual-networks-classic",
      name: "Virtual Networks (Classic)",
      file: "virtual-networks-classic.svg",
    },
    {
      slug: "virtual-networks",
      name: "Virtual Networks",
      file: "virtual-networks.svg",
    },
    {
      slug: "virtual-router",
      name: "Virtual Router",
      file: "virtual-router.svg",
    },
    {
      slug: "virtual-visits-builder",
      name: "Virtual Visits Builder",
      file: "virtual-visits-builder.svg",
    },
    {
      slug: "virtual-wan-hub",
      name: "Virtual WAN Hub",
      file: "virtual-wan-hub.svg",
    },
    { slug: "virtual-wans", name: "Virtual WANs", file: "virtual-wans.svg" },
    {
      slug: "vm-app-definitions",
      name: "VM App Definitions",
      file: "vm-app-definitions.svg",
    },
    {
      slug: "vm-app-versions",
      name: "VM App Versions",
      file: "vm-app-versions.svg",
    },
    {
      slug: "vm-image-version",
      name: "VM Image Version",
      file: "vm-image-version.svg",
    },
    {
      slug: "vm-images-classic",
      name: "VM Images (Classic)",
      file: "vm-images-classic.svg",
    },
    { slug: "vm-scale-sets", name: "VM Scale Sets", file: "vm-scale-sets.svg" },
    {
      slug: "vnet-appliance",
      name: "VNet Appliance",
      file: "vnet-appliance.svg",
    },
    {
      slug: "vpnclientwindows",
      name: "VPNClientWindows",
      file: "vpnclientwindows.svg",
    },
    { slug: "wac-installer", name: "WAC Installer", file: "wac-installer.svg" },
    { slug: "wac", name: "WAC", file: "wac.svg" },
    {
      slug: "web-app-database",
      name: "Web App + Database",
      file: "web-app-database.svg",
    },
    {
      slug: "web-application-firewall-policies-waf",
      name: "Web Application Firewall Policies(WAF)",
      file: "web-application-firewall-policies-waf.svg",
    },
    { slug: "web-jobs", name: "Web Jobs", file: "web-jobs.svg" },
    { slug: "web-slots", name: "Web Slots", file: "web-slots.svg" },
    { slug: "web-test", name: "Web Test", file: "web-test.svg" },
    { slug: "website-power", name: "Website Power", file: "website-power.svg" },
    {
      slug: "website-staging",
      name: "Website Staging",
      file: "website-staging.svg",
    },
    {
      slug: "windows-notification-services",
      name: "Windows Notification Services",
      file: "windows-notification-services.svg",
    },
    {
      slug: "windows10-core-services",
      name: "Windows10 Core Services",
      file: "windows10-core-services.svg",
    },
    { slug: "workbooks", name: "Workbooks", file: "workbooks.svg" },
    {
      slug: "worker-container-app",
      name: "Worker Container App",
      file: "worker-container-app.svg",
    },
    { slug: "workflow", name: "Workflow", file: "workflow.svg" },
    {
      slug: "workload-orchestration",
      name: "Workload Orchestration",
      file: "workload-orchestration.svg",
    },
    {
      slug: "workspace-gateway",
      name: "Workspace Gateway",
      file: "workspace-gateway.svg",
    },
    {
      slug: "workspaces-00400",
      name: "Workspaces",
      file: "workspaces-00400.svg",
    },
    { slug: "workspaces", name: "Workspaces", file: "workspaces.svg" },
  ],
}

export default manifest
