/**
 * Scans plugins/<slug>/{plugin.json,manifest.ts,icons/*.svg} and writes a
 * static registry to lib/plugins/registry.generated.ts, imported normally
 * by the rest of the app — the same principle as
 * generate-archimate-icon-pack.ts: discovery happens once, at build/commit
 * time, not via a dynamic fs read at request time (Vercel's file tracer
 * can't reliably discover files touched by a dynamic import(), and there's
 * no `tsx` runtime available to transpile plugins/*.ts files in a deployed
 * serverless function anyway).
 *
 * Never touches the *.svg files themselves: those stay under
 * plugins/<slug>/icons/ and are served on demand by
 * app/api/plugins/[pluginSlug]/icons/[iconSlug]/route.ts, via fs.readFileSync
 * on a path built exclusively from the `file` field validated here — never
 * from a request parameter (see that route for the detail of this
 * guarantee).
 *
 * Run via `pnpm --filter server gen:plugin-registry`. Fails loudly on: a
 * missing plugin.json/manifest.ts, invalid JSON/Zod validation, plugin.json
 * whose `id` doesn't match its folder name, a manifest.ts icon referencing a
 * file missing from icons/, an icons/ file not referenced by any manifest
 * entry (orphan asset), or an icon slug declared by more than one plugin
 * (icon slugs are globally unique — they're the archispark_image value).
 */

import { readdirSync, readFileSync, existsSync, writeFileSync } from "node:fs"
import path from "node:path"
import { pathToFileURL } from "node:url"
import * as prettier from "prettier"
import {
  PluginJsonSchema,
  IconPluginManifestSchema,
} from "../lib/plugins/schema"

const ROOT = path.resolve(import.meta.dirname, "../../..")
const PLUGINS_DIR = path.join(ROOT, "plugins")
const OUT_FILE = path.join(
  import.meta.dirname,
  "../lib/plugins/registry.generated.ts"
)

const PRETTIER_OPTIONS: prettier.Options = {
  parser: "typescript",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 80,
}

async function main(): Promise<void> {
  const slugs = readdirSync(PLUGINS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort()

  const entries: string[] = []
  const seenIconSlugs = new Map<string, string>() // iconSlug -> owning pluginSlug

  for (const slug of slugs) {
    const dir = path.join(PLUGINS_DIR, slug)

    const pluginJsonPath = path.join(dir, "plugin.json")
    if (!existsSync(pluginJsonPath))
      throw new Error(`plugins/${slug}/plugin.json is missing`)
    const pluginJson = PluginJsonSchema.parse(
      JSON.parse(readFileSync(pluginJsonPath, "utf8"))
    )
    if (pluginJson.id !== slug)
      throw new Error(
        `plugins/${slug}/plugin.json: id "${pluginJson.id}" must equal the folder name "${slug}"`
      )

    const manifestPath = path.join(dir, "manifest.ts")
    if (!existsSync(manifestPath))
      throw new Error(`plugins/${slug}/manifest.ts is missing`)
    // manifest.ts's IconPluginManifest import is type-only and erased, so
    // this dynamic import never needs to resolve @workspace/types at
    // runtime — see manifest.ts's own header comment.
    const mod = (await import(pathToFileURL(manifestPath).href)) as {
      default: unknown
    }
    const manifest = IconPluginManifestSchema.parse(mod.default)

    const iconsDir = path.join(dir, "icons")
    const actualFiles = new Set(readdirSync(iconsDir))
    const referencedFiles = new Set<string>()
    const iconEntries: string[] = []

    for (const icon of manifest.icons) {
      if (!actualFiles.has(icon.file))
        throw new Error(
          `plugins/${slug}/manifest.ts references missing file '${icon.file}'`
        )
      referencedFiles.add(icon.file)

      const owner = seenIconSlugs.get(icon.slug)
      if (owner)
        throw new Error(
          `Icon slug '${icon.slug}' is declared by both '${owner}' and '${slug}' — icon slugs must be globally unique.`
        )
      seenIconSlugs.set(icon.slug, slug)

      iconEntries.push(
        `{ slug: ${JSON.stringify(icon.slug)}, name: ${JSON.stringify(icon.name)}, file: ${JSON.stringify(icon.file)} }`
      )
    }

    const orphans = [...actualFiles].filter((f) => !referencedFiles.has(f))
    if (orphans.length > 0)
      throw new Error(
        `plugins/${slug}/icons/ has unreferenced file(s): ${orphans.join(", ")}`
      )

    entries.push(
      `${JSON.stringify(slug)}: {
        slug: ${JSON.stringify(slug)},
        name: ${JSON.stringify(pluginJson.name)},
        version: ${JSON.stringify(pluginJson.version)},
        description: ${JSON.stringify(pluginJson.description ?? null)},
        type: ${JSON.stringify(pluginJson.type)},
        icons: [${iconEntries.join(",\n")}],
      }`
    )
  }

  const src = `// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit.
// Run \`pnpm --filter server gen:plugin-registry\` after changing plugins/**.
import type { PluginRegistryEntry } from "./types"

export const PLUGIN_REGISTRY: Record<string, PluginRegistryEntry> = {
  ${entries.join(",\n")}
}
`
  const formatted = await prettier.format(src, PRETTIER_OPTIONS)
  writeFileSync(OUT_FILE, formatted)

  console.log(
    `Generated ${slugs.length} plugin(s), ${seenIconSlugs.size} icon(s) -> ${OUT_FILE}`
  )
}

main()
