/**
 * Generator for the AWS / Azure / GCP icon plugins (plugins/{aws,azure,gcp}/).
 *
 * Reads the vendor icon sets from a local --source directory (not part of
 * the repo — point it at a folder containing AWS/, Azure/, GCP/ subfolders
 * with the official AWS Architecture Icons, Microsoft Azure service icons,
 * and Google Cloud product icons), normalizes filenames into stable slugs
 * (see lib/cloud-icon-slug.ts), and rewrites each vendor's
 * plugins/<vendor>/{icons/*.svg,manifest.ts} wholesale (a full rewrite, not
 * an incremental diff — manifest.ts is a generated artifact, not a history).
 *
 * Icon slugs must stay globally unique across all plugins (see
 * generate-plugin-registry.ts) — this script only dedupes *within* one
 * vendor (see cloud-icon-slug.ts's dedupeBySlug). A cross-vendor collision
 * from a source refresh surfaces as a hard failure from
 * `pnpm gen:plugin-registry`, requiring the same kind of manual
 * disambiguation scripts/migrate-image-packs-to-plugins.ts's
 * SLUG_OVERRIDES applied once during the original DB -> plugins cutover.
 *
 * Run via `pnpm --filter server gen:cloud-icon-packs -- --source <dir>`,
 * then `pnpm --filter server gen:plugin-registry`. Not part of the build —
 * its output is committed to the repo like any other source file.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs"
import path from "node:path"
import {
  normalizeAwsIcons,
  normalizeAzureIcons,
  normalizeGcpIcons,
  type CloudIcon,
  type SourceFile,
} from "./lib/cloud-icon-slug"

const ROOT = path.resolve(import.meta.dirname, "../../..")
const PLUGINS_DIR = path.join(ROOT, "plugins")

interface Vendor {
  slug: string
  sourceDir: string
  name: string
  description: string
  normalize: (files: SourceFile[]) => CloudIcon[]
}

const VENDORS: Vendor[] = [
  {
    slug: "aws",
    sourceDir: "AWS",
    name: "AWS Icons",
    description:
      "Official AWS Architecture Service Icons, for use in ReactFlow diagrams.",
    normalize: normalizeAwsIcons,
  },
  {
    slug: "azure",
    sourceDir: "Azure",
    name: "Azure Icons",
    description:
      "Official Microsoft Azure service icons, for use in ReactFlow diagrams.",
    normalize: normalizeAzureIcons,
  },
  {
    slug: "gcp",
    sourceDir: "GCP",
    name: "GCP Icons",
    description:
      "Official Google Cloud product icons, for use in ReactFlow diagrams.",
    normalize: normalizeGcpIcons,
  },
]

function parseSourceArg(): string {
  const flagIndex = process.argv.indexOf("--source")
  const value = flagIndex >= 0 ? process.argv[flagIndex + 1] : undefined
  if (!value) {
    throw new Error(
      "Missing --source <dir>: path to the folder containing AWS/, Azure/, GCP/ subfolders."
    )
  }
  return path.resolve(value.replace(/^~/, process.env["HOME"] ?? "~"))
}

function readSvgFiles(dir: string): SourceFile[] {
  return readdirSync(dir)
    .filter((filename) => filename.toLowerCase().endsWith(".svg"))
    .map((filename) => ({
      filename,
      content: readFileSync(path.join(dir, filename), "utf8"),
    }))
}

/** Keeps a plugin's existing version across regenerations — bump it by hand
 *  in plugin.json when a vendor's icon set changes meaningfully. */
function existingVersion(pluginJsonPath: string): string {
  if (!existsSync(pluginJsonPath)) return "1.0.0"
  const parsed = JSON.parse(readFileSync(pluginJsonPath, "utf8")) as {
    version?: string
  }
  return parsed.version ?? "1.0.0"
}

function main(): void {
  const sourceRoot = parseSourceArg()

  for (const vendor of VENDORS) {
    const sourceDir = path.join(sourceRoot, vendor.sourceDir)
    const files = readSvgFiles(sourceDir)
    const icons = vendor
      .normalize(files)
      .sort((a, b) => a.slug.localeCompare(b.slug))

    const pluginDir = path.join(PLUGINS_DIR, vendor.slug)
    const iconsDir = path.join(pluginDir, "icons")
    mkdirSync(iconsDir, { recursive: true })

    for (const icon of icons) {
      writeFileSync(
        path.join(iconsDir, `${icon.slug}.svg`),
        icon.content + "\n"
      )
    }

    const pluginJsonPath = path.join(pluginDir, "plugin.json")
    writeFileSync(
      pluginJsonPath,
      JSON.stringify(
        {
          id: vendor.slug,
          name: vendor.name,
          version: existingVersion(pluginJsonPath),
          description: vendor.description,
          type: "icon-pack",
        },
        null,
        2
      ) + "\n"
    )

    const manifestIcons = icons
      .map(
        (icon) =>
          `  { slug: ${JSON.stringify(icon.slug)}, name: ${JSON.stringify(icon.name)}, file: ${JSON.stringify(`${icon.slug}.svg`)} },`
      )
      .join("\n")
    writeFileSync(
      path.join(pluginDir, "manifest.ts"),
      `// AUTO-GENERATED by scripts/generate-cloud-icon-packs.ts — do not edit.
// Import of TYPE only, erased at compile time — never needs to be resolved
// at runtime. Relative path because plugins/ is not a pnpm workspace member
// (no @workspace/types specifier resolvable here).
import type { IconPluginManifest } from "../../packages/types/src/index"

const manifest: IconPluginManifest = {
  icons: [
${manifestIcons}
  ],
}

export default manifest
`
    )

    console.log(
      `[${vendor.slug}] ${files.length} source files -> ${icons.length} icons (${pluginDir})`
    )
  }

  console.log("Run `pnpm --filter server gen:plugin-registry` next.")
}

main()
